apiVersion: v2
name: platform-core
version: 0.0.1
dependencies:
  - name: platformCore
    version: 0.0.1
annotations:
  images: |
    - name: coredns
      image: coredns/coredns:
    - name: coredns-autoscaler
      image: registry.k8s.io/cpa/cluster-proportional-autoscaler:1.8.5
    - name: local-volume-node-cleanup-controller
      image: gcr.io/k8s-staging-sig-storage/local-volume-node-cleanup:canary
    - name: local-static-provisioner
      image: registry.k8s.io/sig-storage/local-volume-provisioner:v2.6.0
    - name: init-udev-rule
      image: alpine:3.15
    - name: dummy-container
      image: alpine:3.15