apiVersion: v2
name: platform-core
version: 0.0.1
dependencies:
  - name: platformCore
    version: 0.0.1
annotations:
  images: |
    - name: local-volume-node-cleanup-controller
      image: gcr.io/k8s-staging-sig-storage/local-volume-node-cleanup:canary
    - name: local-static-provisioner
      image: registry.k8s.io/sig-storage/local-volume-provisioner:v2.7.0