platformCore:
  corednsEnabled: false
  localStorageEnabled: false
  eksUdevEnabled: false
  cleanUpControllerEnabled: false
  turndown:
    enabled: "false"
  localStaticProvisioner:
    classes:
      - name: nvme-ssd
        hostDir: /dev/disk/kubernetes
        storageClass: true
    nodeSelector:
      dedicated-nodes: local-storage
    tolerations:
      - key: "dedicated-nodes"
        operator: "Equal"
        value: "local-storage"
        effect: "NoSchedule"