---
{{- $sharedSecret := randAscii 32 | b64enc }}
{{- $cookieSecret := randAscii 32 | b64enc }}
{{- $idpClientSecret := randAscii 32 | b64enc }}
{{- $sharedSecretData := (lookup "v1" "Secret" .Release.Namespace .Values.pomeriumPlatform.pomerium.config.existingSharedSecret ).data }}
{{- if and $sharedSecretData (not .Values.pomeriumPlatform.pomerium.config.forceGenerateServiceSecrets) }}
{{- $sharedSecret = (index $sharedSecretData "SHARED_SECRET" | b64dec) }}
{{- $cookieSecret = (index $sharedSecretData "COOKIE_SECRET" | b64dec) }}
{{- $idpClientSecret = (index $sharedSecretData "IDP_CLIENT_SECRET" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pomeriumPlatform.pomerium.config.existingSharedSecret }}
  labels:
    app.kubernetes.io/name: pomerium
{{- if .Values.pomeriumPlatform.pomerium.config.extraSharedSecretLabels }}
    {{- range $key, $value := .Values.pomeriumPlatform.pomerium.config.extraSharedSecretLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
type: Opaque
data:
  SHARED_SECRET: {{ $sharedSecret | b64enc }}
  COOKIE_SECRET: {{ $cookieSecret | b64enc }}
  IDP_CLIENT_SECRET: {{ $idpClientSecret | b64enc }}