{{- if eq .Values.lokiPlatform.loki.minioSecretEnabled "true" }}
{{- $password := (randAscii 32 | b64enc) }}
{{- $username := (randAscii 32 | b64enc) }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace "loki-platform-minio-bucket-secret").data }}
{{- if $secretData }}
{{- $password = (index $secretData "MINIO_LOKI_SECRET" | b64dec) }}
{{- $username = (index $secretData "MINIO_LOKI_USER" | b64dec) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "loki-platform-minio-bucket-secret"
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  MINIO_LOKI_USER: {{ $username | b64enc }}
  MINIO_LOKI_SECRET: {{ $password | b64enc }}
{{- end }}