apiVersion: v2
name: k8s-platform-addon-operator
version: 0.1.0 # will be overwritten from Jenkinsfile
appVersion: "${VERSION}.${currentBuild.number}_${env.BRANCH_NAME}_${shortCommit()}" # will be overwritten from Jenkinsfile
annotations:
  images: |

    ## CERT-MANAGER IMAGES
    - name: cert-manager
      image: quay.io/jetstack/cert-manager-controller:v1.12.4
    - name: cainjector
      image: quay.io/jetstack/cert-manager-cainjector:v1.12.4
    - name: webhook
      image: quay.io/jetstack/cert-manager-webhook:v1.12.4
    - name: acmesolver
      image: quay.io/jetstack/cert-manager-acmesolver:v1.12.4
    - name: cert-manager-ctl
      image: quay.io/jetstack/cert-manager-ctl:v1.12.4
  
    ## CloudNativePG IMAGES
    - name: q-cnpg-timescale-15
      image: artifactory.qvantel.net/q-cnpg-timescale:15.7-1_5_master_e1aa9a467
    - name: q-cnpg-timescale-16
      image: artifactory.qvantel.net/q-cnpg-timescale:16.3-1_5_master_e1aa9a467
    - name: cloudnative-pg
      image: ghcr.io/cloudnative-pg/cloudnative-pg:1.22.2
    
    ## CONSUL IMAGES
    - name: consul
      image: docker.io/hashicorp/consul:1.14.4
    - name: consul-k8s-control-plane
      image: docker.io/hashicorp/consul-k8s-control-plane:1.0.3
    - name: consul-dataplane
      image: docker.io/hashicorp/consul-dataplane:1.0.1
    - name: envoy
      image: docker.io/envoyproxy/envoy:v1.23.1
    
    ## ELASTICSEARCH IMAGES
    - name: elasticsearch
      image: artifactory.qvantel.net/helm-k8s-elasticsearch:7.16.2
    - name: kibana
      image: artifactory.qvantel.net/helm-k8s-kibana:7.16.2
    - name: eck-operator
      image: artifactory.qvantel.net/helm-k8s-eck-operator:2.2.0
    - name: filebeat
      image: artifactory.qvantel.net/helm-k8s-filebeat:7.16.2
    - name: logstash
      image: artifactory.qvantel.net/helm-k8s-logstash:7.16.2
    
    ## EXTERNAL-DNS IMAGES
    - name: external-dns
      image: docker.io/bitnami/external-dns:0.13.4-debian-11-r2
    
    ## ISTIO IMAGES
    - name: pilot
      image: docker.io/istio/pilot:1.17.6
    - name: proxyv2
      image: docker.io/istio/proxyv2:1.17.6

    ## LOKI IMAGES
    - name: loki
      image: docker.io/grafana/loki:2.9.2
    
    ## MARIADB IMAGES
    - name: mariadb-operator
      image: ghcr.io/mariadb-operator/mariadb-operator:v0.0.28
    - name: mariadb
      image: docker.io/mariadb:10.4.33
    
    ## METRICS-PLATFORM IMAGES
    - name: metrics-server
      image: registry.k8s.io/metrics-server/metrics-server:v0.6.4
    - name: addon-resizer
      image: registry.k8s.io/autoscaling/addon-resizer:1.8.19

    ## VAULT IMAGES
    - name: vault
      image: docker.io/hashicorp/vault:1.12.1
    - name: vault-secrets-webhook
      image: ghcr.io/banzaicloud/vault-secrets-webhook:1.18.0
    - name: platform-tools
      image: artifactory.qvantel.net/k8s-platform-tools:latest
    
    ## VECTOR IMAGES
    - name: fluent-bit
      image: cr.fluentbit.io/fluent/fluent-bit:2.2.2
    - name: configmap-reload
      image: ghcr.io/jimmidyson/configmap-reload:v0.11.1
    - name: vector
      image: docker.io/timberio/vector:0.36.0-distroless-libc
    - name: haproxy-alpine
      image: docker.io/haproxytech/haproxy-alpine:2.6.12
