---
logLevel: info
globalConfig:
  someGlobalValue: "put your value"
modulesConfig:  
  auroraMysqlDbEnabled: "false"
  externalDnsEnabled: "false"
  kafkaPlatformEnabled: "false"
  vaultConfigurationEnabled: "false"
  auroraMysqlDb:
    configurationRequired: "check module documentation for configuration options"
  externalDns:
    configurationRequired: "check module documentation for configuration options"
  kafkaPlatform:
    configurationRequired: "check module documentation for configuration options"
  vaultConfiguration:
    configurationRequired: "check module documentation for configuration options"

