logLevel: info
addonOperatorNamespace: "platform"
platformCore: {}
helmIgnoreRelease: "k8s-platform"
imageBase: "artifactory.qvantel.net/k8s-platform-addon-operator"
deployment:
  replicas: 1
  additionalEnvironmentVars: []
  nodeSelector:
  #cluster-controller: "true"
  tolerations:
  # - effect: NoSchedule
  #   key: CriticalAddonsOnly
  #   operator: Exists
  # - effect: NoExecute
  #   key: node.kubernetes.io/not-ready
  #   operator: Exists
  #   tolerationSeconds: 300
  # - effect: NoExecute
  #   key: node.kubernetes.io/unreachable
  #   operator: Exists
  #   tolerationSeconds: 300
globalConfig:
  # one of  'dev', 'test', 'perf', 'prod'
  configurationProfile: "test"
  platformMasters: false
  ingressBaseUrl: "some-env.qvantel.solutions"
  kubernetesVersion: "1.25"
modulesConfig:
  platformCore:
    configurationRequired: "check module documentation for configuration options"
  apisixPlatformEnabled: "false"
  apisixPlatform:
    configurationRequired: "check module documentation for configuration options"
  awsPlatformEnabled: "false"
  awsPlatform:
    configurationRequired: "check module documentation for configuration options"
  certPlatformEnabled: "false"
  certPlatform:
    configurationRequired: "check module documentation for configuration options"
  ciliumPlatformEnabled: "false"
  ciliumPlatform:
    configurationRequired: "check module documentation for configuration options"
  cnpgPostgresPlatformEnabled: "false"
  cnpgPostgresPlatform:
    images:
      cloudnative-pg:
        registry: ghcr.io
        repository: cloudnative-pg/cloudnative-pg
        tag: "1.22.2"
      q-cnpg-timescale-15:
        registry: artifactory.qvantel.net
        repository: q-cnpg-timescale
        tag: "15.7-1_5_master_e1aa9a467"
      q-cnpg-timescale-16:    
        registry: artifactory.qvantel.net
        repository: q-cnpg-timescale
        tag: "16.3-1_5_master_e1aa9a467"
  consulPlatformEnabled: "false"
  consulPlatform:
    configurationRequired: "check module documentation for configuration options"
  dbManagementEnabled: "false"
  dbManagement:
    configurationRequired: "check module documentation for configuration options"
  elasticsearchPlatformEnabled: "false"
  elasticsearchPlatform:
    configurationRequired: "check module documentation for configuration options"
  externalDnsEnabled: "false"
  externalDns:
    configurationRequired: "check module documentation for configuration options"
  grafanaPlatformEnabled: "false"
  grafanaPlatform:
    configurationRequired: "check module documentation for configuration options"
  instanaPlatformEnabled: "false"
  instanaPlatform:
    instana-agent:
      agent:
        image:
          name: platform-artifactory.qvantel.net/agent/static
          tag: 1.276.0
      leaderElector:
        image:
          name: platform-artifactory.qvantel.net/instana/leader-elector
          tag: 0.5.19
      k8s_sensor:
        image:
          name: platform-artifactory.qvantel.net/instana/k8sensor
          tag: ffb74e9
  istioIngressEnabled: "false"
  istioIngress:
    configurationRequired: "check module documentation for configuration options"
  istioPlatformEnabled: "false"
  istioPlatform:
    configurationRequired: "check module documentation for configuration options"
  ksixPlatformEnabled: "false"
  ksixPlatform:
    configurationRequired: "check module documentation for configuration options"
  kafkaPlatformEnabled: "false"
  kafkaPlatform:
    strimziHelmVersion: "0.27.1"
  kasopePlatformEnabled: "false"
  kasopePlatform:
    configurationRequired: "check module documentation for configuration options"
  kyvernoPlatformEnabled: "false"
  kyvernoPlatform:
    configurationRequired: "check module documentation for configuration options"
  lokiPlatformEnabled: "false"
  lokiPlatform:
    loki:
      loki:
        image:
          registry: artifactory.qvantel.net
          repository: platform/grafana/loki
          tag: 2.9.2
  keycloakPlatformEnabled: "false"
  keycloakPlatform:
    configurationRequired: "check module documentation for configuration options"
  mariadbPlatformEnabled: "false"
  mariadbPlatform:
    configurationRequired: "check module documentation for configuration options"
  mariadbOperatorPlatformEnabled: "false"
  mariadbOperatorPlatform:
    images:
      mariadb:
        registry: artifactory.qvantel.net
        repository: platform/library/mariadb
        tag: 10.4.33
  metricsPlatformEnabled: "false"
  metricsPlatform:
    configurationRequired: "check module documentation for configuration options"
  mongodbPlatformEnabled: "false"
  mongodbPlatform:
    configurationRequired: "check module documentation for configuration options"
  monitoringPlatformEnabled: "false"
  monitoringPlatform:
    configurationRequired: "check module documentation for configuration options"
  perconaPmmPlatformEnabled: "false"
  perconaPmmPlatform:
    configurationRequired: "check module documentation for configuration options"
  pomeriumPlatformEnabled: "false"
  pomeriumPlatform:
    configurationRequired: "check module documentation for configuration options"
  postgresPlatformEnabled: "false"
  postgresPlatform:
    configurationRequired: "check module documentation for configuration options"
  qvantelGlueEnabled: "false"
  rabbitmqPlatformEnabled: "false"
  rabbitmqPlatform:
    configurationRequired: "check module documentation for configuration options"
  redisPlatformEnabled: "false"
  redisPlatform: {}
  redisPcdPlatformEnabled: "false"
  redisPcdPlatform:
    configurationRequired: "check module documentation for configuration options"
  redisCbsMasterPlatformEnabled: "false"
  redisCbsMasterPlatform:
    configurationRequired: "check module documentation for configuration options"
  redisCbsControllerPlatformEnabled: "false"
  redisCbsControllerPlatform:
    configurationRequired: "check module documentation for configuration options"
  rancherPlatformEnabled: "false"
  rancherPlatform:
    configurationRequired: "check module documentation for configuration options"
  sftpEnabled: "false"
  sftp:
    configurationRequired: "check module documentation for configuration options"
  sftpgoPlatformEnabled: "false"
  sftpgoPlatform:
    configurationRequired: "check module documentation for configuration options"
  traefikIngressEnabled: "false"
  traefikIngress:
    configurationRequired: "check module documentation for configuration options"
  vaultPlatformEnabled: "false"
  vaultPlatform:
    configurationRequired: "check module documentation for configuration options"
  vectorPlatformEnabled: "false"
  vectorPlatform:
    configurationRequired: "check module documentation for configuration options"
