apiVersion: v2
name: monitoringPlatform
version: 0.0.1
dependencies:
  - name: grafana
    condition: grafana.enabled
    version: ~6.24.1
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    condition: promtail.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "^3.11.0"
  - name: loki
    condition: loki.enabled
    version: ^2.10.1
    repository: https://grafana.github.io/helm-charts
  - name: prometheus
    condition: prometheus.enabled
    version: "~15.8.5"
    repository:  "https://prometheus-community.github.io/helm-charts"
