apiVersion: platform-vault.qvantel.com/v1
kind: AclPolicy
metadata:
  name: apps-default-policy
spec:
  policy-hcl: >-
    {{ printf "path \"secret/{{identity.entity.aliases.{kubernetes-accessor}.metadata.service_account_namespace}}/{{identity.entity.aliases.{kubernetes-accessor}.metadata.service_account_name}}\" {" }}
      capabilities = [ "read" ]
    }
    {{ printf "path \"secret/{{identity.entity.aliases.{kubernetes-accessor}.metadata.service_account_namespace}}/{{identity.entity.aliases.{kubernetes-accessor}.metadata.service_account_name}}/*\" {" }}
      capabilities = [ "read" ]
    }
    {{ printf "path \"database/creds/{{identity.entity.aliases.{kubernetes-accessor}.metadata.service_account_namespace}}-{{identity.entity.aliases.{kubernetes-accessor}.metadata.service_account_name}}*\" {" }}
      capabilities = [ "read" ]
    }
    {{ printf "path \"rabbitmq/creds/{{identity.entity.aliases.{kubernetes-accessor}.metadata.service_account_namespace}}-{{identity.entity.aliases.{kubernetes-accessor}.metadata.service_account_name}}*\" {" }}
      capabilities = [ "read" ]
    }
    path "auth/token/renew-self" {
        capabilities = ["update"]
    }
    path "database/creds/readwrite-role-redis*" {
        capabilities = ["read"]
    }
  computed-values:
    - name: "kubernetes-accessor"
      expression: "vault_get_accessor('kubernetes/')"