apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: vault-platform
    app.kubernetes.io/name: vault
  name: vault
  namespace: platform
spec:
  ports:
  - name: http
    port: 8200
    protocol: TCP
    targetPort: 8200
  - name: https-internal
    port: 8201
    protocol: TCP
    targetPort: 8201
  selector:
    app.kubernetes.io/instance: vault-platform
    app.kubernetes.io/name: vault
    component: server
  sessionAffinity: None
  type: ClusterIP