{{- if and ( .Values.vaultPlatform.vault.global.enabled ) ( .Values.vaultPlatform.useBackwardsCompatibilityService )  }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-port: http
    platform.qvantel.com/consul-service-port: "8200"
  labels:
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/name: vault
  name: vault
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - name: http
    port: 8200
    protocol: TCP
    targetPort: 8200
  - name: https-internal
    port: 8201
    protocol: TCP
    targetPort: 8201
  selector:
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/name: vault
    component: server
  sessionAffinity: None
  type: ClusterIP
{{- end }}