apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Values.global.helmReleaseNamePrefix}}vault-platform-vault-secrets-webhook-ca
spec:
  isCA: true
  commonName: ca.vault-secrets-webhook.cert-manager
  dnsNames:
    - {{.Values.global.helmReleaseNamePrefix}}vault-platform-vault-secrets-webhook
    - {{.Values.global.helmReleaseNamePrefix}}vault-platform-vault-secrets-webhook.{{.Values.global.platformNamespace}}
    - {{.Values.global.helmReleaseNamePrefix}}vault-platform-vault-secrets-webhook.{{.Values.global.platformNamespace}}.svc
  duration: {{.Values.vaultPlatform.webhookCertificateDuration }}
  renewBefore: 360h # 15d
  issuerRef:
    name: qvantel-ca-issuer
    kind: Issuer
    group: cert-manager.io
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: {{.Values.global.helmReleaseNamePrefix}}vault-platform-vault-secrets-webhook-ca