apiVersion: v1
data:
  init.sh: |
    #!/bin/sh

    CURL_OPT="-sk --connect-timeout 10"
    VAULT_ADDR="http://localhost:8200"
    CURL_RESULT="/tmp/curl.result"

    # Kubernetes configuration, possibility to override via env
    [ -z "${KUBE_API}" ] && KUBE_API=https://${KUBERNETES_PORT_443_TCP_ADDR}:${KUBERNETES_PORT_443_TCP_PORT}
    [ -z "${VAULT_K8S_NAMESPACE}" ] && VAULT_K8S_NAMESPACE=platform
    [ -z "${KUBE_SECRETS_KEY}" ] && KUBE_SECRETS_KEY=vault-keys
    [ -z "${VAULT_INIT_NODE}" ] && VAULT_INIT_NODE="vault-platform-0"
    [ -z "${VAULT_K8S_POD_NAME}" ] && VAULT_K8S_POD_NAME="vault-platform-0"
    # VAULT_K8S_POD_NAME, VAULT_INIT_NODE and VAULT_K8S_NAMESPACE are set in pod spec in values.yaml.mako

    qlog () {
        echo "$(date -Iseconds) [vault-init] ${@}"
    }

    if [ "${VAULT_K8S_POD_NAME}" = "${VAULT_INIT_NODE}" ] ; then

        HEALTH_STATUS="$(curl ${CURL_OPT} -w '%{http_code}' -o ${CURL_RESULT} ${VAULT_ADDR}/v1/sys/health)"

        while [ "${HEALTH_STATUS}" = "000" ]; do
            qlog "Current vault response: ${HEALTH_STATUS}. waiting 5 sec";
            sleep 5;
            HEALTH_STATUS="$(curl ${CURL_OPT} -w '%{http_code}' -o ${CURL_RESULT} ${VAULT_ADDR}/v1/sys/health)"
        done

        HEALTH=$(cat ${CURL_RESULT})
        INITIALIZED=$(echo ${HEALTH} | jq -r '.initialized')

        if [ "${INITIALIZED}" = "false" ]; then
            qlog "Vault is not initialized."

{{- if .Values.vaultPlatform.autoUnseal }}
            INIT_STATUS="$(curl ${CURL_OPT} --request PUT -w '%{http_code}' -o ${CURL_RESULT} --data '{"recovery_shares": 1, "recovery_threshold": 1}' ${VAULT_ADDR}/v1/sys/init)"
{{- else }}
            INIT_STATUS="$(curl ${CURL_OPT} --request PUT -w '%{http_code}' -o ${CURL_RESULT} --data '{"secret_shares": 1, "secret_threshold": 1}' ${VAULT_ADDR}/v1/sys/init)"
{{- end }}
            qlog "Initialized vault with status code: ${INIT_STATUS} $(cat ${CURL_RESULT})"

            if [ "${INIT_STATUS}" = "200" ]; then
                RECOVERY_KEY="$(jq -r '.keys[0] // empty' ${CURL_RESULT})"
                ROOT_TOKEN="$(jq -r '.root_token // empty' ${CURL_RESULT})"
                RECOVERY_OUTPUT="$(cat ${CURL_RESULT} | base64 )"

                kubectl delete secret "$KUBE_SECRETS_KEY" -n "$VAULT_K8S_NAMESPACE" --ignore-not-found

                kubectl create secret generic "$KUBE_SECRETS_KEY" -n "$VAULT_K8S_NAMESPACE" \
                    --from-literal=recovery_output="$RECOVERY_OUTPUT"   \
                    --from-literal=root_token="$ROOT_TOKEN"
            else
                qlog "Unexpected vault status : ${INIT_STATUS}. Aborting"
                exit 1
            fi
        elif [ "${INITIALIZED}" = "true" ]; then
            qlog "Vault is already initialized. Status : ${HEALTH}"
        else
            qlog "Unknown vault status : ${HEALTH}. Aborting"
            exit 1
        fi
    else
        qlog "This (${VAULT_K8S_POD_NAME}) is not Vault initialization node. Skipping Vault initialization."
    fi

{{- if .Values.vaultPlatform.k8sUnseal }}
    qlog "Starting vault automatic unseal from k8s secrets"
{{- else }}
    qlog "Vault automatic unseal from k8s secrets not configured"
    while true; do qlog "sleeping"; sleep infinity; done
    exit 0 # this is normally never reached
{{- end }}

    # wait until we can fetch vault unseal key from k8s secrets
    until kubectl get secrets -n "$VAULT_K8S_NAMESPACE" "$KUBE_SECRETS_KEY" > /dev/null 2>&1; do
        qlog "Vault k8s secret not available yet, retrying in 5 seconds"
        sleep 5
    done
    KEY=`kubectl get secrets -n "$VAULT_K8S_NAMESPACE" "$KUBE_SECRETS_KEY" -o jsonpath="{.data.recovery_output}" | base64 -d | base64 -d | jq -r '.keys[0]'`
    if [ "x$KEY" = "x" ]; then
        qlog "Unable to get vault unseal key. Exiting with failure"
        exit 1
    fi
    # after we have the key, wait in a loop and unseal if vault is sealed
    qlog "Entering loop, checking vault status every 5 seconds"
    while sleep 5; do
        HEALTH_STATUS="$(curl ${CURL_OPT} -w '%{http_code}' -o ${CURL_RESULT} ${VAULT_ADDR}/v1/sys/health)"

        while [ "${HEALTH_STATUS}" = "000" ]; do
            qlog "Vault not available yet, sleeping 5 sec"
            sleep 5
            HEALTH_STATUS="$(curl ${CURL_OPT} -w '%{http_code}' -o ${CURL_RESULT} ${VAULT_ADDR}/v1/sys/health)"
        done

        HEALTH=$(cat ${CURL_RESULT})
        INITIALIZED=$(echo ${HEALTH} | jq -r '.initialized')
        SEALED=$(echo ${HEALTH} | jq -r '.sealed')

        if [ "${INITIALIZED}" = "false" ]; then
            qlog "Vault is not initialized. Exiting with failure"
            exit 1
        elif [ "${INITIALIZED}" = "true" ]; then
            if [ "${SEALED}" = "true" ]; then
                qlog "Vault is sealed. Trying to unseal";
                kubectl exec -it -n "$VAULT_K8S_NAMESPACE" "$VAULT_K8S_POD_NAME" -c vault -- vault operator unseal $KEY
            fi
        else
            qlog "Unknown vault health response: ${HEALTH}. Exiting with failure"
            exit 1
        fi
    done

kind: ConfigMap
metadata:
  name: vault-auto-init-config
  namespace: {{.Release.Namespace}}
