apiVersion: v1
kind: Service
metadata:
  name: smartsearch-elasticsearch-client
  namespace: platform
  labels:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: smartsearch
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: smartsearch
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
