{{- template "elasticsearchPlatform.logsearchEnabled" . -}}
{{- if .logsearchEnabled -}}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: logsearch
  namespace: platform
  annotations:
    helm.sh/hook: post-install,post-upgrade,pre-delete
    helm.sh/hook-weight: "4"
    eck.k8s.elastic.co/downward-node-labels: "topology.kubernetes.io/zone"
spec:
  version: {{ .Values.elasticsearchPlatform.logsearch.image.tag }}
  volumeClaimDeletePolicy: {{ .Values.elasticsearchPlatform.logsearch.volumePolicy }}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: logsearch
    count: {{ .Values.elasticsearchPlatform.logsearch.count }}
    config:
      {{- if eq .Values.elasticsearchPlatform.logsearch.zoneAffinity "true" }}
      node.attr.zone: ${ZONE}
      cluster.routing.allocation.awareness.attributes: k8s_node_name,zone
      {{- end }}
      node.attr.data: warm
      node.attr.type: warm
      node.roles: ["master", "data", "ingest", "data_hot", "data_warm"]
      node.store.allow_mmap: false
      logger.org.elasticsearch: {{ .Values.elasticsearchPlatform.logsearch.logLevel }}
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.elasticsearchPlatform.logsearch.resources.storage }}
    podTemplate:
      spec:
{{  .Values.elasticsearchPlatform.logsearch.initContainers | indent 8  }}
        containers:
          - name: elasticsearch
            image: "{{ .Values.elasticsearchPlatform.logsearch.image.repository }}:{{ .Values.elasticsearchPlatform.logsearch.image.tag }}"
            resources:
              requests:
                memory: {{ .Values.elasticsearchPlatform.logsearch.resources.requests.memory }}
                cpu: {{ .Values.elasticsearchPlatform.logsearch.resources.requests.cpu }}
              limits:
                memory: {{ .Values.elasticsearchPlatform.logsearch.resources.limits.memory }}
                cpu: {{ .Values.elasticsearchPlatform.logsearch.resources.limits.cpu }}
{{- if eq .Values.elasticsearchPlatform.logsearch.zoneAffinity "true"  }}
{{  .Values.elasticsearchPlatform.logsearch.zoneConf | indent 12  }}
{{  .Values.elasticsearchPlatform.logsearch.topologySpreadConstraints | indent 8  }}
{{- end }}
  - name: logsearch-cold
    count: 1
    config:
      {{- if eq .Values.elasticsearchPlatform.logsearch.zoneAffinity "true" }}
      node.attr.zone: ${ZONE}
      cluster.routing.allocation.awareness.attributes: k8s_node_name,zone
      {{- end }}
      node.attr.data: cold
      node.attr.type: cold
      node.roles: ["data_cold", "data_content"]
      node.store.allow_mmap: false
      logger.org.elasticsearch: {{ .Values.elasticsearchPlatform.logsearch.logLevel }}
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.elasticsearchPlatform.logsearch.resources.storage }}
    podTemplate:
      spec: 
{{  .Values.elasticsearchPlatform.logsearch.initContainers | indent 8  }}
        containers:
          - name: elasticsearch
            image: "{{ .Values.elasticsearchPlatform.logsearch.image.repository }}:{{ .Values.elasticsearchPlatform.logsearch.image.tag }}"
            resources:
              requests:
                memory: {{ .Values.elasticsearchPlatform.logsearch.resources.requests.memory }}
                cpu: {{ .Values.elasticsearchPlatform.logsearch.resources.requests.cpu }}
              limits:
                memory: {{ .Values.elasticsearchPlatform.logsearch.resources.limits.memory }}
                cpu: {{ .Values.elasticsearchPlatform.logsearch.resources.limits.cpu }}
{{- if eq .Values.elasticsearchPlatform.logsearch.zoneAffinity "true"  }}
{{  .Values.elasticsearchPlatform.logsearch.zoneConf | indent 12  }}
{{  .Values.elasticsearchPlatform.logsearch.topologySpreadConstraints | indent 8  }}
{{- end }}
  podDisruptionBudget:
    spec:
      minAvailable: 1
      selector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name: logsearch
{{- end }}