{{- if .Values.elasticsearchPlatform.clusters }}
{{- range keys .Values.elasticsearchPlatform.clusters  }}
{{- $current := get $.Values.elasticsearchPlatform.clusters . }}
{{- if $current.enabled }}

---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ . }}
  annotations:
    eck.k8s.elastic.co/downward-node-labels: "topology.kubernetes.io/zone"
spec:
  {{- tpl $current.spec $ | nindent 2 }}

{{- end }}
{{- end }}
{{- end }}