{{- template "elasticsearchPlatform.kibanaEnabled" . -}}
{{- if .kibanaEnabled -}}
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: {{.Release.Namespace}}
spec:
  {{- range .Values.elasticsearchPlatform.configKibana }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}