{{- $password := (randAscii 32 | b64enc) }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace "legacy-kibana-readonly-user").data }}
{{- if $secretData }}
{{- $password = (index $secretData "password" | b64dec) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "legacy-kibana-readonly-user"
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  username: {{ "readonly" | b64enc }}
  password: {{ $password | b64enc }}