{{- if and .Values.lokiPlatform.loki.objectStorageSecret .Values.lokiPlatform.loki.objectStorageSecret.create }}
{{- $password := (randAscii 32 | b64enc) }}
{{- $username := (randAscii 32 | b64enc) }}
{{- $secretName := .Values.lokiPlatform.loki.objectStorageSecret.secretName }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace $secretName).data }}
{{- if $secretData }}
{{- $password = (index $secretData "OBJECT_STORAGE_SECRET" | b64dec) }}
{{- $username = (index $secretData "OBJECT_STORAGE_USER" | b64dec) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  OBJECT_STORAGE_USER: {{ $username | b64enc }}
  OBJECT_STORAGE_SECRET: {{ $password | b64enc }}
{{- end }}