## WARNING! 
## This is just a dummy Chart.yaml in order to support "helm dt" tooling. 
## Proper Chart.yaml will be generated in runtime from Chart.yaml.mako file and it will override this file
## However it should contain all actual versions of dependencies charts

apiVersion: v2
name: kafkaPlatform
version: 0.0.1
dependencies:
  - name: strimzi-kafka-operator    
    version: 0.43.0
    alias: strimzi-kafka-operator-043
    repository: https://strimzi.io/charts/
    condition: strimzi-kafka-operator.enabled
  - name: strimzi-kafka-operator
    version: 0.45.1
    alias: strimzi-kafka-operator-0451
    repository: https://strimzi.io/charts/
    condition: strimzi-kafka-operator.enabled
  - name: kafka-ui
    version: 1.5.1
    repository: https://kafbat.github.io/helm-charts/