---
{{- $username := default (randAscii 9 | b64enc) .Values.keycloakPlatform.adminUsername }}
{{- $password := default (randAscii 32 | b64enc) .Values.keycloakPlatform.adminPassword }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace "keycloak-admin-secret").data }}
{{- if $secretData }}
{{- $username = (index $secretData "KEYCLOAK_ADMIN" | b64dec) }}
{{- $password = (index $secretData "KEYCLOAK_ADMIN_PASSWORD" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "keycloak-admin-secret"
type: Opaque
data:
  KEYCLOAK_ADMIN: {{ $username | b64enc }}
  KEYCLOAK_ADMIN_PASSWORD: {{ $password | b64enc }}
---
{{- $limitedusername := default (randAscii 9 | b64enc) .Values.keycloakPlatform.limitedAdminUsername }}
{{- $limitedpassword := default (randAscii 32 | b64enc) .Values.keycloakPlatform.limitedAdminPassword }}
{{- $limitedSecretData := (lookup "v1" "Secret" .Release.Namespace "keycloak-limited-admin-secret").data }}
{{- if $limitedSecretData }}
{{- $limitedusername = (index $limitedSecretData "KEYCLOAK_LIMITED_ADMIN" | b64dec) }}
{{- $limitedpassword = (index $limitedSecretData "KEYCLOAK_LIMITED_ADMIN_PASSWORD" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "keycloak-limited-admin-secret"
type: Opaque
data:
  KEYCLOAK_LIMITED_ADMIN: {{ $limitedusername | b64enc }}
  KEYCLOAK_LIMITED_ADMIN_PASSWORD: {{ $limitedpassword | b64enc }}