---
{{- $username := default (randAscii 32 | b64enc) .Values.keycloakPlatform.adminUsername }}
{{- $password := default (randAscii 32 | b64enc) .Values.keycloakPlatform.adminPassword }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace "keycloak-admin-secret").data }}
{{- if $secretData }}
{{- $username = (index $secretData "KEYCLOAK_ADMIN" | b64dec) }}
{{- $password = (index $secretData "KEYCLOAK_ADMIN_PASSWORD" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "keycloak-admin-secret"
type: Opaque
data:
  KEYCLOAK_ADMIN: {{ $username | b64enc }}
  KEYCLOAK_ADMIN_PASSWORD: {{ $password | b64enc }}