apiVersion: platform.qvantel.com/v1
kind: SqlInstaller
metadata:
  annotations:
    platform.qvantel.com/retry-count: "100"
  name: qvaa-keycloak-postgresql-installer
spec:
  type: postgresql
  db-provision-sql: 
    - "CREATE ROLE db_keycloak NOLOGIN"
    - "GRANT db_keycloak TO CURRENT_USER"
    - "CREATE DATABASE keycloak WITH OWNER db_keycloak"
  db-username: postgres
  db-password: "{postgres-password}"
  db-url: "postgresql://{postgres-user}:{postgres-password}@{{ .Values.keycloakPlatform.database.name }}.platform.svc:5432/postgres"
  computed-values:
    - name: "postgres-password"
      expression: "k8s_get_secret_value('{{ .Values.keycloakPlatform.database.name }}-superuser', '{{ $.Release.Namespace }}', 'password')"
    - name: "postgres-user"
      expression: "k8s_get_secret_value('{{ .Values.keycloakPlatform.database.name }}-superuser', '{{ $.Release.Namespace }}', 'username')"