apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: "qvaa-configurator-{{ .Release.Name }}"
  namespace: {{.Release.Namespace}}
spec:
  {{ tpl .Values.keycloakPlatform.configurator.spec . | nindent 2 }}