---
kind: ConfigMap
apiVersion: v1
metadata:
  name: configurator-configmap
  namespace: {{.Release.Namespace}}
data: 
  configurator.yml: |
    ---
    realms:
      {{- tpl (toYaml .Values.keycloakPlatform.configurator.configmapValues.realms) . | nindent 4 }}