apiVersion: v1
kind: Service
metadata:
  name: qvaa-proxy-80
  namespace: platform
spec:
  selector:
    # this must match pod label. there are other ways of matching but this is a simple one.
    app: qvaa-keycloak
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080