---
kind: ConfigMap
apiVersion: v1
metadata:
  name: qvaa-keycloak-configmap
  namespace: {{.Release.Namespace}}
binaryData: 
  truststore.jks: {{.Values.keycloakPlatform.deployment.trustStoreContent}}