{{- if .Values.cnpgPostgresPlatform }}
{{- range $name, $cluster := .Values.cnpgPostgresPlatform.clusters }}
{{- if and $cluster.spec $cluster.spec.postgresql $cluster.spec.postgresql.parameters (hasKey $cluster.spec.postgresql.parameters "pg_partman_bgw.dbname") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-partitions-alerts-{{ $name }}
  namespace: platform
  labels:
    cnpg.io/reload: ""
data:
  partitions-alerts-queries: |
    partitions_alerts:
      query: |
        select current_database() as cur_db, parent_table as table_name, extract(EPOCH FROM (now() - maintenance_last_run)) as last_run_sec from partman.part_config;
      metrics:
        - cur_db:
            usage: "LABEL"
            description: "Database Name"
        - table_name:
            usage: "LABEL"
            description: "Partitioned table Name"
        - last_run_sec:
            usage: "GAUGE"
            description: "Last successful maintenance execution in seconds"
      target_databases:
{{- $dbs := split "," (index $cluster.spec.postgresql.parameters "pg_partman_bgw.dbname") }}
{{- range $db := $dbs }}
        - {{ trim $db }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}