{{- if .Values.cnpgPostgresPlatform }}
{{- $root := . }}
{{- range keys .Values.cnpgPostgresPlatform.clusters  }}
{{- $current := get $.Values.cnpgPostgresPlatform.clusters . }}
{{- if $current.enabled }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ . }}
  {{- with $current.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ . }}
    app.kubernetes.io/instance: {{ . }}
    app.kubernetes.io/part-of: cloudnative-pg
  {{- with $current.additionalLabels }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml $current.spec | nindent 2 }}
  {{- if $root.Values.global.awsRole}}
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: {{ $root.Values.global.awsRole }}
  {{- end }}

{{- if $root.Values.cnpgPostgresPlatform.monitoringPlatformEnabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    cnpg.io/cluster: {{ . }}
    release: "{{ $root.Values.global.helmReleaseNamePrefix }}monitoring-platform"
  name: {{ . }}-monitor
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: {{ . }}
{{- end }}


{{- if and $current.spec.backup $current.scheduledBackup }}

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ . }}-scheduled-backups
spec:
  schedule: {{ $current.scheduledBackup }}
  backupOwnerReference: self
  cluster:
    name: {{ . }}
  immediate: true
  target: {{ $current.spec.backup.target | default "prefer-standby" }}
  
{{- end }}

{{- end }}
{{- end }}
{{- end }}
