{{- if .Values.cnpgPostgresPlatform }}
{{- $root := . }}
{{- range keys .Values.cnpgPostgresPlatform.clusters  }}
{{- $current := get $.Values.cnpgPostgresPlatform.clusters . }}
{{- if $current.enabled }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ . }}
  {{- with $current.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ . }}
    app.kubernetes.io/instance: {{ . }}
    app.kubernetes.io/part-of: cloudnative-pg
  {{- with $current.additionalLabels }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml $current.spec | nindent 2 }}

{{- if $current.podMonitorEnabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    cnpg.io/cluster: {{ . }}
    release: "{{ $root.Values.global.helmReleaseNamePrefix }}monitoring-platform"
  name: {{ . }}-monitor
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: {{ . }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
