apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mongodb
  name: mongodb
  namespace: platform
spec:
  ports:
  - name: default
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app.kubernetes.io/name: mongodb
  sessionAffinity: None
  type: ClusterIP
