kind: Service
apiVersion: v1
metadata:
  name: consul-consul-server-{{.Release.Namespace}}
spec:
  type: ExternalName
  externalName: {{.Values.global.helmReleaseNamePrefix}}consul-platform-consul-server.{{.Release.Namespace}}.svc.cluster.local
  ports:
  - name: http
    port: 8500
    protocol: TCP
    targetPort: 8500
  - name: serflan-tcp
    port: 8301
    protocol: TCP
    targetPort: 8301
  - name: serfwan-tcp
    port: 8302
    protocol: TCP
    targetPort: 8302
  - name: server
    port: 8300
    protocol: TCP
    targetPort: 8300
  - name: dns-tcp
    port: 8600
    protocol: TCP