
{{- if eq .Values.global.clusterwideResources "false" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: consul
  namespace: {{.Release.Namespace}}
rules:
  - apiGroups: [""]
    verbs:
      - get
      - list
      - watch
    resources:
      - pods
      - namespaces
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: consul
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: consul
subjects:
  - kind: ServiceAccount
    name: consul
    namespace: {{.Release.Namespace}}
{{- else}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-{{.Release.Namespace}}
rules:
  - apiGroups: [""]
    verbs:
      - get
      - list
      - watch
    resources:
      - pods
      - namespaces
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-{{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: consul-{{.Release.Namespace}}
subjects:
  - kind: ServiceAccount
    name: consul
    namespace: {{.Release.Namespace}}
{{- end }} 