---
{{- if eq .Values.global.deployOperators "true" }}
{{- $access_key_id:= (randAscii 32 | b64enc) }}
{{- $secret_access_key:= (randAscii 32 | b64enc) }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace "platform-minio-readwrite").data }}
{{- if $secretData }}
{{- $access_key_id = (index $secretData "readwriteUser" | b64dec) }}
{{- $secret_access_key = (index $secretData "readwritePassword" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
 name: platform-minio-readwrite-mariadb
 namespace: {{.Release.Namespace}}
type: Opaque
data:
  readwriteUser: {{ $access_key_id | b64enc }}
  readwritePassword: {{ $secret_access_key | b64enc }}
{{- end }}