apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
data:
  loki-stack-datasource.yaml: |-
    apiVersion: 1
    datasources:
{{- if .Values.monitoringPlatform.loki.enabled }}
    - name: Loki
      type: loki
      access: proxy
      url: http://monitoring-platform-loki.platform.svc:3100
      version: 1
      isDefault: true
      jsonData:
        maxLines: 1000
{{- end }}
{{- if .Values.monitoringPlatform.prometheus.enabled }}
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://monitoring-platform-prometheus-server.platform.svc
      version: 1
      isDefault: false
{{- end }}