
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- if .Values.globalConfig.awsRole}}
    eks.amazonaws.com/role-arn: {{ .Values.globalConfig.awsRole }}
  {{- end }}

{{- if eq .Values.globalConfig.clusterwideResources "true" }}  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addon-operator-{{ .Release.Namespace }}
rules:
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - "*"
- nonResourceURLs:
    - "*"
  verbs:
    - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: addon-operator-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addon-operator-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: platform
    namespace: {{ .Release.Namespace }}
{{- else}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: addon-operator-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: addon-operator-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: addon-operator-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: platform
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: addon-operator-{{ .Values.globalConfig.appsNamespace }}
  namespace: {{ .Values.globalConfig.appsNamespace }}
rules:
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: addon-operator-{{ .Values.globalConfig.appsNamespace }}
  namespace: {{ .Values.globalConfig.appsNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: addon-operator-{{ .Values.globalConfig.appsNamespace }}
subjects:
  - kind: ServiceAccount
    name: platform
    namespace: {{ .Release.Namespace }}
{{- end }} 