apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- if .Values.globalConfig.awsRole}}
    eks.amazonaws.com/role-arn: {{ .Values.globalConfig.awsRole }}
  {{- end }}
---
{{- if eq .Values.globalConfig.clusterwideResources "true" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addon-operator-{{ .Release.Namespace }}
rules:
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - "*"
- nonResourceURLs:
    - "*"
  verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: addon-operator-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addon-operator-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: platform
    namespace: {{ .Release.Namespace }}
{{- else}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: addon-operator-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: platform
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: addon-operator-{{ .Values.globalConfig.appsNamespace }}
  namespace: {{ .Values.globalConfig.appsNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: platform
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: addon-operator-{{ .Release.Namespace }}-additional
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
    - cassandra.datastax.com
    - cert-manager.io
    - core.strimzi.io
    - kafka.strimzi.io
    - k8ssandra.io
    - medusa.k8ssandra.io
    - monitoring.coreos.com
    - networking.istio.io
    - platform-vault.qvantel.com
    - platform.qvantel.com
    - postgresql.cnpg.io
    - qvantel.com
    - reaper.k8ssandra.io
    - replication.k8ssandra.io
    - telemetry.istio.io
  resources:
    - "*"
  verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: addon-operator-{{ .Release.Namespace }}-additional
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: addon-operator-{{ .Release.Namespace }}-additional
subjects:
  - kind: ServiceAccount
    name: platform
    namespace: {{ .Release.Namespace }}
{{- end }}
---
{{- if and (eq .Values.globalConfig.deployOperators "false") (eq .Values.globalConfig.clusterwideResources "false") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: addon-operator-{{ .Values.globalConfig.operatorNamespace }}-configuration-reader
  namespace: {{ .Values.globalConfig.operatorNamespace }}
rules:
- apiGroups: [""]
  resources:
    - secrets
    - configmaps
  verbs:
    - get
    - list
    - watch
 - apiGroups:
    - monitoring.coreos.com
  resources:
    - servicemonitors
  verbs:
    - "*" 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: addon-operator-{{ .Values.globalConfig.operatorNamespace }}-configuration-reader
  namespace: {{ .Values.globalConfig.operatorNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: addon-operator-{{ .Values.globalConfig.operatorNamespace }}-configuration-reader
subjects:
  - kind: ServiceAccount
    name: platform
    namespace: {{ .Release.Namespace }}
{{- end }}