---
apiVersion: v1
kind: ConfigMap
metadata:
  name: addon-operator
  namespace: {{ .Values.addonOperatorNamespace }}
data:
  global: {{ print "|\n" (.Values.globalConfig | toYaml | indent 4) }}

  platformCoreEnabled: "true"
  {{- if .Values.modulesConfig.platformCore }}
  platformCore: {{ print "|\n" (.Values.modulesConfig.platformCore | toYaml | indent 4) }}
  {{- end }}

  apisixPlatformEnabled: "{{ .Values.modulesConfig.apisixPlatformEnabled }}"
  {{- if .Values.modulesConfig.apisixPlatform }}
  apisixPlatform: {{ print "|\n" (.Values.modulesConfig.apisixPlatform | toYaml | indent 4) }}
  {{- end }}
  
  awsPlatformEnabled: "{{ .Values.modulesConfig.awsPlatformEnabled }}"
  {{- if .Values.modulesConfig.awsPlatform }}
  awsPlatform: {{ print "|\n" (.Values.modulesConfig.awsPlatform | toYaml | indent 4) }}
  {{- end }}

  certPlatformEnabled: "{{ .Values.modulesConfig.certPlatformEnabled }}"
  {{- if .Values.modulesConfig.certPlatform }}
  certPlatform: {{ print "|\n" (.Values.modulesConfig.certPlatform | toYaml | indent 4) }}
  {{- end }}

  cnpgPostgresPlatformEnabled: "{{ .Values.modulesConfig.cnpgPostgresPlatformEnabled }}"
  {{- if .Values.modulesConfig.cnpgPostgresPlatform }}
  cnpgPostgresPlatform: {{ print "|\n" (.Values.modulesConfig.cnpgPostgresPlatform | toYaml | indent 4) }}
  {{- end }}

  consulPlatformEnabled: "{{ .Values.modulesConfig.consulPlatformEnabled }}"
  {{- if .Values.modulesConfig.consulPlatform }}
  consulPlatform: {{ print "|\n" (.Values.modulesConfig.consulPlatform | toYaml | indent 4) }}
  {{- end }}

  elasticsearchPlatformEnabled: "{{ .Values.modulesConfig.elasticsearchPlatformEnabled }}"
  {{- if .Values.modulesConfig.elasticsearchPlatform }}
  elasticsearchPlatform: {{ print "|\n" (.Values.modulesConfig.elasticsearchPlatform | toYaml | indent 4) }}
  {{- end }}

  externalDnsEnabled: "{{ .Values.modulesConfig.externalDnsEnabled }}"
  {{- if .Values.modulesConfig.externalDns }}
  externalDns: {{ print "|\n" (.Values.modulesConfig.externalDns | toYaml | indent 4) }}
  {{- end }}
  
  instanaPlatformEnabled: "{{ .Values.modulesConfig.instanaPlatformEnabled }}"
  {{- if .Values.modulesConfig.instanaPlatform }}
  instanaPlatform: {{ print "|\n" (.Values.modulesConfig.instanaPlatform | toYaml | indent 4) }}
  {{- end }}

  istioIngressEnabled: "{{ .Values.modulesConfig.istioIngressEnabled }}"
  {{- if .Values.modulesConfig.istioIngress }}
  istioIngress: {{ print "|\n" (.Values.modulesConfig.istioIngress | toYaml | indent 4) }}
  {{- end }}

  istioPlatformEnabled: "{{ .Values.modulesConfig.istioPlatformEnabled }}"  
  {{- if .Values.modulesConfig.istioPlatform }}
  istioPlatform: {{ print "|\n" (.Values.modulesConfig.istioPlatform | toYaml | indent 4) }}
  {{- end }}

  ksixPlatformEnabled: "{{ .Values.modulesConfig.ksixPlatformEnabled }}"  
  {{- if .Values.modulesConfig.ksixPlatform }}
  ksixPlatform: {{ print "|\n" (.Values.modulesConfig.ksixPlatform | toYaml | indent 4) }}
  {{- end }}

  kafkaPlatformEnabled: "{{ .Values.modulesConfig.kafkaPlatformEnabled }}"  
  {{- if .Values.modulesConfig.kafkaPlatform }}
  kafkaPlatform: {{ print "|\n" (.Values.modulesConfig.kafkaPlatform | toYaml | indent 4) }}
  {{- end }}
  
  kasopePlatformEnabled: "{{ .Values.modulesConfig.kasopePlatformEnabled }}"
  {{- if .Values.modulesConfig.kasopePlatform }}
  kasopePlatform: {{ print "|\n" (.Values.modulesConfig.kasopePlatform | toYaml | indent 4) }}
  {{- end }}

  keycloakPlatformEnabled: "{{ .Values.modulesConfig.keycloakPlatformEnabled }}"
  {{- if .Values.modulesConfig.keycloakPlatform }}
  keycloakPlatform: {{ print "|\n" (.Values.modulesConfig.keycloakPlatform | toYaml | indent 4) }}
  {{- end }}
  
  kyvernoPlatformEnabled: "{{ .Values.modulesConfig.kyvernoPlatformEnabled }}"
  {{- if .Values.modulesConfig.kyvernoPlatform }}
  kyvernoPlatform: {{ print "|\n" (.Values.modulesConfig.kyvernoPlatform | toYaml | indent 4) }}
  {{- end }}

  lokiPlatformEnabled: "{{ .Values.modulesConfig.lokiPlatformEnabled }}"
  {{- if .Values.modulesConfig.lokiPlatform }}
  lokiPlatform: {{ print "|\n" (.Values.modulesConfig.lokiPlatform | toYaml | indent 4) }}
  {{- end }}

  mariadbPlatformEnabled: "{{ .Values.modulesConfig.mariadbPlatformEnabled }}"
  {{- if .Values.modulesConfig.mariadbPlatform }}
  mariadbPlatform: {{ print "|\n" (.Values.modulesConfig.mariadbPlatform | toYaml | indent 4) }}
  {{- end }}

  mariadbOperatorPlatformEnabled: "{{ .Values.modulesConfig.mariadbOperatorPlatformEnabled }}"
  {{- if .Values.modulesConfig.mariadbOperatorPlatform }}
  mariadbOperatorPlatform: {{ print "|\n" (.Values.modulesConfig.mariadbOperatorPlatform | toYaml | indent 4) }}
  {{- end }}

  metricsPlatformEnabled: "{{ .Values.modulesConfig.metricsPlatformEnabled }}"
  {{- if .Values.modulesConfig.metricsPlatform }}
  metricsPlatform: {{ print "|\n" (.Values.modulesConfig.metricsPlatform | toYaml | indent 4) }}
  {{- end }}

  mongodbPlatformEnabled: "{{ .Values.modulesConfig.mongodbPlatformEnabled }}"
  {{- if .Values.modulesConfig.mongodbPlatform }}
  mongodbPlatform: {{ print "|\n" (.Values.modulesConfig.mongodbPlatform | toYaml | indent 4) }}
  {{- end }}

  monitoringPlatformEnabled: "{{ .Values.modulesConfig.monitoringPlatformEnabled }}"
  {{- if .Values.modulesConfig.monitoringPlatform }}
  monitoringPlatform: {{ print "|\n" (.Values.modulesConfig.monitoringPlatform | toYaml | indent 4) }}
  {{- end }}

  perconaPmmPlatformEnabled: "{{ .Values.modulesConfig.perconaPmmPlatformEnabled }}"
  {{- if .Values.modulesConfig.perconaPmmPlatform }}
  perconaPmmPlatform: {{ print "|\n" (.Values.modulesConfig.perconaPmmPlatform | toYaml | indent 4) }}
  {{- end }}

  pomeriumPlatformEnabled: "{{ .Values.modulesConfig.pomeriumPlatformEnabled }}"
  {{- if .Values.modulesConfig.pomeriumPlatform }}
  pomeriumPlatform: {{ print "|\n" (.Values.modulesConfig.pomeriumPlatform | toYaml | indent 4) }}
  {{- end }}
  
  postgresPlatformEnabled: "{{ .Values.modulesConfig.postgresPlatformEnabled }}"
  {{- if .Values.modulesConfig.postgresPlatform }}
  postgresPlatform: {{ print "|\n" (.Values.modulesConfig.postgresPlatform | toYaml | indent 4) }}
  {{- end }}

  qvantelGlueEnabled: "{{ .Values.modulesConfig.qvantelGlueEnabled }}"
  {{- if .Values.modulesConfig.qvantelGlue }}
  qvantelGlue: {{ print "|\n" (.Values.modulesConfig.qvantelGlue | toYaml | indent 4) }}
  {{- end }}

  rabbitmqPlatformEnabled: "{{ .Values.modulesConfig.rabbitmqPlatformEnabled }}"
  {{- if .Values.modulesConfig.rabbitmqPlatform }}
  rabbitmqPlatform: {{ print "|\n" (.Values.modulesConfig.rabbitmqPlatform | toYaml | indent 4) }}
  {{- end }}

  redisPlatformEnabled: "{{ .Values.modulesConfig.redisPlatformEnabled }}"
  {{- if .Values.modulesConfig.redisPlatform }}
  redisPlatform: {{ print "|\n" (.Values.modulesConfig.redisPlatform | toYaml | indent 4) }}
  {{- end }}

  rancherPlatformEnabled: "{{ .Values.modulesConfig.rancherPlatformEnabled }}"
  {{- if .Values.modulesConfig.rancherPlatform }}
  rancherPlatform: {{ print "|\n" (.Values.modulesConfig.rancherPlatform | toYaml | indent 4) }}
  {{- end }}

  sftpEnabled: "{{ .Values.modulesConfig.sftpEnabled }}"
  {{- if .Values.modulesConfig.sftp }}
  sftp: {{ print "|\n" (.Values.modulesConfig.sftp | toYaml | indent 4) }}
  {{- end }}

  sftpgoPlatformEnabled: "{{ .Values.modulesConfig.sftpgoPlatformEnabled }}"
  {{- if .Values.modulesConfig.sftpgoPlatform }}
  sftpgoPlatform: {{ print "|\n" (.Values.modulesConfig.sftpgoPlatform | toYaml | indent 4) }}
  {{- end }}

  vaultPlatformEnabled: "{{ .Values.modulesConfig.vaultPlatformEnabled }}"
  {{- if .Values.modulesConfig.vaultPlatform }}
  vaultPlatform: {{ print "|\n" (.Values.modulesConfig.vaultPlatform | toYaml | indent 4) }}
  {{- end }}

  vectorPlatformEnabled: "{{ .Values.modulesConfig.vectorPlatformEnabled }}"
  {{- if .Values.modulesConfig.vectorPlatform }}
  vectorPlatform: {{ print "|\n" (.Values.modulesConfig.vectorPlatform | toYaml | indent 4) }}
  {{- end }}


