
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- if .Values.platformCore.awsRole}}
    eks.amazonaws.com/role-arn: {{ .Values.platformCore.awsRole }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addon-operator
rules:
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - "*"
- nonResourceURLs:
    - "*"
  verbs:
    - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: addon-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addon-operator
subjects:
  - kind: ServiceAccount
    name: platform
    namespace: {{ .Release.Namespace }}