---
apiVersion: v1
kind: ConfigMap
metadata:
  name: addon-operator
  namespace: {{ .Values.addonOperatorNamespace }}
data:
  global: {{ print "|\n" (.Values.globalConfig | toYaml | indent 4) }}
  auroraMysqlDbEnabled: "{{ .Values.modulesConfig.auroraMysqlDbEnabled }}"
  cassandraPlatformEnabled: "{{ .Values.modulesConfig.cassandraPlatformEnabled }}"
  externalDnsEnabled: "{{ .Values.modulesConfig.externalDnsEnabled }}"
  kafkaPlatformEnabled: "{{ .Values.modulesConfig.kafkaPlatformEnabled }}"
  vaultConfigurationEnabled: "{{ .Values.modulesConfig.vaultConfigurationEnabled }}"
  qinstallersEnabled: "{{ .Values.modulesConfig.qinstallersEnabled }}"
  auroraMysqlDb: {{ print "|\n" (.Values.modulesConfig.auroraMysqlDb | toYaml | indent 4) }}
  cassandraPlatform: {{ print "|\n" (.Values.modulesConfig.cassandraPlatform | toYaml | indent 4) }}
  externalDns: {{ print "|\n" (.Values.modulesConfig.externalDns | toYaml | indent 4) }}
  kafkaPlatform: {{ print "|\n" (.Values.modulesConfig.kafkaPlatform | toYaml | indent 4) }}
  vaultConfiguration: {{ print "|\n" (.Values.modulesConfig.vaultConfiguration | toYaml | indent 4) }}
