---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addon-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: addon-operator
spec:
  replicas: {{ .Values.deployment.replicas}}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: addon-operator
  template:
    metadata:
      labels:
        app: addon-operator
    spec:
      containers:
      - name: addon-operator
        image: {{ .Values.imageBase }}:{{ .Values.imageVersion | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        env:
          - name: ADDON_OPERATOR_DEPLOY_RESOURCES
            value: "{{ .Values.deployResources }}"
          - name: ADDON_OPERATOR_NAMESPACE
            value: {{ .Values.addonOperatorNamespace }}
          - name: LOG_LEVEL
            value: {{ .Values.logLevel }}
          - name: HELM_IGNORE_RELEASE
            value: {{ .Values.helmIgnoreRelease }}
          - name: HELM_RELEASE_NAME_PREFIX
            value: {{ .Values.globalConfig.helmReleaseNamePrefix }}
          - name: INSIDE_CLUSTER
            value: "true"
          {{- range .Values.deployment.additionalEnvironmentVars }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9650
      serviceAccountName: platform
      {{ if .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- tpl .Values.deployment.nodeSelector . | nindent 8 }}
      {{- end }}
      {{ if .Values.deployment.tolerations }}
      tolerations:
        {{- tpl .Values.deployment.tolerations . | nindent 8 }}
      {{- end }}
---
{{ if eq .Values.modulesConfig.shutdownOperatorEnabled "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shutdown-addon-operator
  namespace: {{ .Values.shutdownOperatorNamespace }}
  labels:
    app: shutdown-addon-operator
spec:
  replicas: {{ .Values.shutdownOperator.deployment.replicas}}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: shutdown-addon-operator
  template:
    metadata:
      labels:
        app: shutdown-addon-operator
    spec:
      containers:
      - name: addon-operator
        image: {{ .Values.imageBase }}:{{ .Values.imageVersion | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        env:
          - name: ADDON_OPERATOR_DEPLOY_RESOURCES
            value: "{{ .Values.deployResources }}"
          - name: ADDON_OPERATOR_NAMESPACE
            value: {{ .Values.shutdownOperatorNamespace }}
          - name: LOG_LEVEL
            value: {{ .Values.shutdownOperator.deployment.logLevel }}
          - name: HELM_IGNORE_RELEASE
            value: {{ .Values.helmIgnoreRelease }}
          - name: HELM_RELEASE_NAME_PREFIX
            value: {{ .Values.globalConfig.helmReleaseNamePrefix }}
          - name: INSIDE_CLUSTER
            value: "true"
          {{- range .Values.shutdownOperator.deployment.additionalEnvironmentVars }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9650
      serviceAccountName: {{ .Values.shutdownOperator.deployment.serviceAccountName }}
      {{ if .Values.shutdownOperator.deployment.nodeSelector }}
      nodeSelector:
        {{- tpl .Values.shutdownOperator.deployment.nodeSelector . | nindent 8 }}
      {{- end }}
      {{ if .Values.shutdownOperator.deployment.tolerations }}
      tolerations:
        {{- tpl .Values.shutdownOperator.deployment.tolerations . | nindent 8 }}
      {{- end }}
{{- end }}