apiVersion: v2
name: minio-platform
version: 0.0.1
dependencies:
  - name: minioPlatform
    version: 0.0.1
annotations:
  images: |
    - name: minio
      image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    - name: mc
      image: quay.io/minio/mc:RELEASE.2025-08-13T08-35-41Z
    