istioPrivateIngress:
  gateway:
    service:
      type: None
  aws:
    enabled: true
    private:
      provider: millicom-non-prod-uat
      region: us-east-1
      vpcId: vpc-00dc70d11da901b4c
      subnets:
        - subnet-00e47289a85a51add
        - subnet-075d4de626d1f68da
        - subnet-05cdb1ad65f9dc874                    
    public:
      provider: millicom-network-uat
      region: us-east-1
      vpcId: vpc-00dc70d11da901b4c
      subnets:
        - subnet-0a8762991261af74c
        - subnet-0b893a19d387312cb


