apiVersion: v2
name: metallb-platform
version: 0.0.1
dependencies:
  - name: metallbPlatform
    version: 0.0.1
annotations:
  images: |
    - name: ffr
      image: quay.io/frrouting/frr:9.1.0
    - name: metallb-speaker
      image: quay.io/metallb/speaker:v0.15.2
    - name: metallb-controller
      image: quay.io/metallb/controller:v0.15.2