{{- if .Values.logsearchPlatform.elasticsearch.global.kibanaEnabled }}
{{- $kibanasecret := (randAscii 32 | b64enc) }}
{{- $platformNamespace := $.Values.global.platformNamespace }}
{{- $kibanasecretData := (lookup "v1" "Secret" $platformNamespace "logsearch-kibana-system").data }}
{{- if $kibanasecretData }}
{{- $kibanasecret = (index $kibanasecretData "kibana-password" | b64dec) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: logsearch-kibana-system
type: Opaque
data:
  kibana-user: {{ "kibana_system" | b64enc }}
  kibana-password: {{ $kibanasecret | b64enc }}
{{- end }}

---
{{- $elasticsecret := (randAscii 32 | b64enc) }}
{{- $platformNamespace := $.Values.global.platformNamespace }}
{{- $elasticsecretData := (lookup "v1" "Secret" $platformNamespace "logsearch-elastic").data }}
{{- if $elasticsecretData }}
{{- $elasticsecret = (index $elasticsecretData "elasticsearch-password" | b64dec) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: logsearch-elastic
type: Opaque
data:
  elastic-user: {{ "elastic" | b64enc }}
  elasticsearch-password: {{ $elasticsecret | b64enc }}