postgresPlatform:
  postgres-operator-ui:
    envs:
      operatorApiUrl: "http://postgres-platform-postgres-operator:8080"
      operatorClusterNameLabel: "cluster-name"
      resourcesVisible: "False"
      targetNamespace: "platform"
      teams:
        - "qvt"
  clusters:
    qvt-postgredb:
      enabled: true
      spec:
        teamId: "qvt"
        dockerImage: artifactory.qvantel.net/qvantel-spilo:2.1-p7.20221130075959_postgres-14_b47cdbd7
        volume:
          size: 150Gi
        numberOfInstances: 2
        resources:
          limits:
            cpu: 1000m
            memory: 6Gi
          requests:
            cpu: 250m
            memory: 256Mi
        postgresql:
          version: "13"