---
{{- $idpClientSecret := (randAscii 32 | b64enc) }}
{{- $sharedSecretData := (lookup "v1" "Secret" .Release.Namespace .Values.sftpgoPlatform.secrets.existingSecretName ).data }}
{{- if and $sharedSecretData (not .Values.sftpgoPlatform.secrets.forceGenerateServiceSecrets) }}
{{- $idpClientSecret = (index $sharedSecretData "SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sftpgoPlatform.secrets.existingSecretName }}
  labels:
    app.kubernetes.io/name: sftpgo
{{- if .Values.sftpgoPlatform.secrets.extraSharedSecretLabels }}
    {{- range $key, $value := .Values.sftpgoPlatform.secrets.extraSharedSecretLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
type: Opaque
data:
  SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET: {{ $idpClientSecret | b64enc }}