apiVersion: v1
kind: Secret
metadata:
  name: "grafana-admin-pass-secret"
type: Opaque
stringData:
  adminUser: admin
  # retrieve the secret data using lookup function and when it doesn't exist, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "grafana-admin-pass-secret") | default dict }}
  {{- $secretData := (get $secretObj "stringData") | default dict }}
  # set $grafanaAdminPassSecret to existing secret data or generate a random one when not exists
  {{- $grafanaAdminPassSecret := (get $secretData "grafana-admin-pass-secret") | default (randAlphaNum 32 | b64enc) }}
  grafanaAdminPassword: {{ $grafanaAdminPassSecret | quote }}