apiVersion: v2
name: cnpg-postgres-platform
version: 0.0.1
dependencies:
  - name: cnpgPostgresPlatform
    version: 0.0.1
annotations:
  images: |  
    - name: q-cnpg-timescale-13
      image: platform.artifactory.qvantel.net/cloudnative-pg/q-cnpg-timescale:13.18-33_1.2.1_202503141111_master_facc7d5c
    - name: q-cnpg-timescale-15
      image: platform.artifactory.qvantel.net/cloudnative-pg/q-cnpg-timescale:15.10-32_1.2.1_202503141111_master_facc7d5c
    - name: q-cnpg-timescale-16
      image: platform.artifactory.qvantel.net/cloudnative-pg/q-cnpg-timescale:16.6-32_1.2.1_202503141111_master_facc7d5c
    - name: q-cnpg-timescale-17
      image: platform.artifactory.qvantel.net/cloudnative-pg/q-cnpg-timescale:17.2-32_1.2.1_202503141111_master_facc7d5c
    - name: cloudnative-pg
      image: ghcr.io/cloudnative-pg/cloudnative-pg:1.24.0
