---
{{- $password := (randAscii 32 | b64enc) }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace "sftpgo-admin-secret").data }}
{{- if $secretData }}
{{- $password = (index $secretData "password" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "sftpgo-admin-secret"
type: Opaque
data:
  username: {{ "platform-admin" | b64enc }}
  password: {{ $password | b64enc }}