{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafbat-ui-configmap
data:
  config.yml: |-
    kafka:
      clusters:
        {{- if .Values.kafkaPlatform.clusters }}
        {{- range keys .Values.kafkaPlatform.clusters }}
        {{- $current := get $.Values.kafkaPlatform.clusters . }}
        {{- if $current.enabled }}
        - name: {{ . }}
          bootstrapServers: {{ . }}-kafka-bootstrap.{{ $root.Release.Namespace }}.svc.cluster.local.:9092
        {{- end }}
        {{- end }}
        {{- end }}
    auth:
      {{- if eq (index .Values.kafkaPlatform "kafka-ui" "auth") "oauth2"}}
      type: OAUTH2
      oauth2:
        client:
          keycloak:
            clientId: kafbat
            clientSecret: "$KAFKA_UI_CLIENT_SECRET"
            scope: openid
            client-name: keycloak
            provider: keycloak
            authorization-grant-type: authorization_code
            issuer-uri: https://auth-{{ $.Values.global.ingressBaseUrl }}/auth/realms/qvantel
            jwk-set-uri: http://qvaa-proxy-80/auth/realms/qvantel/protocol/openid-connect/certs
            user-name-attribute: preferred_username
            custom-params:
              type: oauth
              roles-field: roles
      {{- else }}
      type: disabled
      {{- end }} 
    management:
      health:
        ldap:
          enabled: false