---
{{- if eq .Values.global.deployOperators "true" }}
{{- $secret := (randAscii 32) }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace "kafka-ui-client-secret").data }}
{{- if $secretData }}
{{- $secret = (index $secretData "KAFKA_UI_CLIENT_SECRET" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "kafka-ui-client-secret"
type: Opaque
data:
  KAFKA_UI_CLIENT_SECRET: {{ $secret | b64enc }}
{{- else }}
## Needed to connect Kafka UI to Keycloak running in shared namespace
---
{{- $secret := (randAscii 32) }}
{{- $secretData := (lookup "v1" "Secret" .Values.global.operatorNamespace "kafka-ui-client-secret").data }}
{{- if $secretData }}
{{- $secret = (index $secretData "KAFKA_UI_CLIENT_SECRET" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "kafka-ui-client-secret"
type: Opaque
data:
  KAFKA_UI_CLIENT_SECRET: {{ $secret | b64enc }}
{{- end }}