{{ if .Values.kafkaPlatform.main-kafka-service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app.kubernetes.io/component: kafka-broker
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: kafka
spec:
  ports:
    - name: tcp-clients
      protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    strimzi.io/broker-role: 'true'
    strimzi.io/cluster: {{ .Values.kafkaPlatform.main-kafka-service.cluster-name }}
    strimzi.io/kind: Kafka
    strimzi.io/name: {{ .Values.kafkaPlatform.main-kafka-service.cluster-name }}-kafka
{{- end }}