{{- if (index  .Values.artifactoryPlatform "artifactory-oss").enabled }}

{{- $username := "admin" }}
{{- $password := randAscii 32 | b64enc }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace "artifactory-oss-admin-secret").data }}
{{- if $secretData }}
{{- $username = (index $secretData "username" | b64dec) }}
{{- $password = (index $secretData "password" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "artifactory-oss-admin-secret"
type: Opaque
data:
  bootstrap.creds: {{ (printf "%s@%s=%s" $username "127.0.0.1" $password) | b64enc }}
  username: {{ $username | b64enc }}
  password: {{ $password | b64enc }}

{{- end }}