apiVersion: v2
name: elasticsearch-platform
version: 0.0.1
dependencies:
  - name: elasticsearchPlatform
    version: 0.0.1
annotations:
  images: |
    - name: elasticsearch
      image: docker.io/library/elasticsearch:7.16.2
    - name: kibana
      image: docker.io/library/kibana:7.16.2
    - name: eck-operator
      image: docker.io/elastic/eck-operator:2.2.0
    - name: filebeat
      image: docker.io/elastic/filebeat:7.16.2
    - name: logstash
      image: docker.io/library/logstash:7.16.2
    - name: loggingsetup
      image: artifactory.qvantel.net/platform/platform-k8s-tools-minimal:1.2.0_4_20c54b53f
