apiVersion: v2
name: elasticsearch-platform
version: 0.0.1
dependencies:
  - name: elasticsearchPlatform
    version: 0.0.1
annotations:
  images: |
    - name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:9.1.5
    - name: kibana
      image: docker.elastic.co/kibana/kibana:9.1.5
    - name: eck-operator
      image: docker.elastic.co/eck/eck-operator:3.1.0
    - name: filebeat
      image: docker.elastic.co/beats/filebeat-oss:9.1.5
    - name: logstash
      image: docker.elastic.co/logstash/logstash:9.1.5
    - name: loggingsetup
      image: platform.artifactory.qvantel.net/platform/platform-k8s-tools-minimal:1.3.3_202509080945_master_90384dcc
