apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: public-ingress-proxy-protocol
  namespace: {{ .Release.Namespace }}
spec:
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
        - name: envoy.filters.listener.tls_inspector
  workloadSelector:
    labels:
      istio: public-ingress
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: private-ingress-proxy-protocol
  namespace: {{ .Release.Namespace }}
spec:
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
        - name: envoy.filters.listener.tls_inspector
  workloadSelector:
    labels:
      istio: private-ingress
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: integrations-ingress-proxy-protocol
  namespace: {{ .Release.Namespace }}
spec:
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.filters.listener.proxy_protocol
        - name: envoy.filters.listener.tls_inspector
  workloadSelector:
    labels:
      istio: integrations-ingress