apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: public-ingress
spec:
  selector:
    istio: public-ingress
  servers:
    - hosts:
      - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
    - hosts:
      - '*'
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: qvantel-wildcard