{{- range .Values.istioIngress.virtualServices.instances }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  {{- $empty := dict}}
  {{- $commonAnnotations := (default $empty $.Values.istioIngress.virtualServices.annotations | deepCopy)}}
  {{- $serviceAnnotations := (default $empty .annotations | deepCopy)}}
  {{- $joinedAnnotations := merge $serviceAnnotations $commonAnnotations }}
  {{- if $joinedAnnotations }}
  annotations:
    {{- toYaml $joinedAnnotations | nindent 4 }}
  {{- end }}
  name: {{ .name }}
  namespace: platform
spec:
  gateways:
  - ingress-gateway
  hosts: 
   - {{ .name }}-{{ $.Values.istioIngress.virtualServices.dnsBase }}
  http: {{ print "\n" (.http | toYaml | indent 2) }}
{{- end }}  
