apiVersion: v2
name: loki-platform
version: 0.0.1
dependencies:
  - name: lokiPlatform
    version: 0.0.1
annotations:
  images: |
    - name: loki
      image: docker.io/grafana/loki:3.5.3
    - name: loki-sidecar
      image: kiwigrid/k8s-sidecar:1.30.7
    - name: memcached
      image: docker.io/library/memcached:1.6.38-alpine