apiVersion: v2
name: grafanaPlatform
version: 0.0.1
dependencies:
#  - name: grafana
#    version: ^6.48.0
#    repository: https://grafana.github.io/helm-charts
  - name: grafana
    version: ^6.48.0
    repository: https://artifactory.qvantel.net/artifactory/helm-platform/