{{- if .Values.kasopePlatform.clusters }}
{{- range keys .Values.kasopePlatform.clusters  }}
{{- $current := get $.Values.kasopePlatform.clusters . }}
{{- if $current.enabled }}
---
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: {{ . }}
spec:
  {{- toYaml $current.spec | nindent 2 }}

{{- end }}
{{- end }}
{{- end }}