{{- if .Values.kasopePlatform.mainCassandraCluster }}
{{- $main := get .Values.kasopePlatform.clusters .Values.kasopePlatform.mainCassandraCluster }}
{{- if $main.enabled }}
{{- $clusterName :=  nospace (default .Values.kasopePlatform.mainCassandraCluster $main.spec.cassandra.clusterName) }}
{{- $dataCenter := first $main.spec.cassandra.datacenters }}

apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-port: native
  labels:
    app: main-cassandra-service
  name: main-cassandra-service
spec:
  clusterIP: None
  ports:
    - name: native
      port: 9042
      protocol: TCP
      targetPort: 9042
    - name: tls-native
      port: 9142
      protocol: TCP
      targetPort: 9142
    - name: mgmt-api
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: prometheus
      port: 9103
      protocol: TCP
      targetPort: 9103
    - name: metrics
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: thrift
      port: 9160
      protocol: TCP
      targetPort: 9160
  selector:
    cassandra.datastax.com/cluster: {{ $clusterName }}
    cassandra.datastax.com/datacenter: {{ $dataCenter.metadata.name }}
  sessionAffinity: None
  type: ClusterIP

{{- end }}
{{- end }}

