
{{- if .Values.kasopePlatform.clusters }}
{{- range $name := keys .Values.kasopePlatform.clusters }}
{{- $current := get $.Values.kasopePlatform.clusters $name }}
{{- if $current.enabled }}
{{- $dc := (index $current.spec.cassandra.datacenters 0).metadata.name }}
{{- if and $current.spec.reaper (hasKey $current.spec.reaper "datacenterAvailability") }}
{{- $availability := (index $current.spec.reaper.datacenterAvailability) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-{{$name}}-reaper-dc-availability
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    spec:
      serviceAccountName: platform
      containers:
      - name: patch-reaper
        image: {{ $.Values.global.containerRegistryBase | default "platform.artifactory.qvantel.net" }}/platform/platform-k8s-tools-minimal:1.3.2_202508131123_master_e140ddde
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for Reaper CR to be created..."
          until kubectl get reaper {{$name}}-{{$dc}}-reaper -n {{ $.Release.Namespace }}; do sleep 5; done
          echo "Patching Reaper..."
          kubectl patch reaper {{$name}}-{{$dc}}-reaper -n {{ $.Release.Namespace }} --type merge -p '{"spec":{"datacenterAvailability":"{{$availability}}"}}'
      restartPolicy: OnFailure
{{- end }}    
{{- end }}
{{- end }}
{{- end }}