{{- if .Values.kasopePlatform.clusters }}
{{- range keys .Values.kasopePlatform.clusters  }}
{{- $current := get $.Values.kasopePlatform.clusters . }}
{{- if $current.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: reaper
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: app
      port: 8080
      protocol: TCP
      targetPort: app
    - name: admin
      port: 8081
      protocol: TCP
      targetPort: admin
  selector:
    app.kubernetes.io/component: reaper
    app.kubernetes.io/managed-by: k8ssandra-operator
    app.kubernetes.io/name: k8ssandra-operator
    app.kubernetes.io/part-of: k8ssandra
  sessionAffinity: None
  type: ClusterIP
{{- end }}
{{- end }}
{{- end }}