apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sqlinstallers.platform-qinstallers.qvantel.com
spec:
  group: platform-qinstallers.qvantel.com
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: sqlinstallers
    # singular name to be used as an alias on the CLI and for display
    singular: sqlinstaller
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: SqlInstaller
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - sqlinsts
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: SQL QInstaller for provisioning of sql database
          required:
            - spec
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                  description: The type of database to provision
                  enum:
                    - postgresql
                    - mariadb
                db-provision-sql:
                  type: array
                  items:
                    type: string
                db-secret-name:
                  type: string
                db-url:
                  type: string
                db-username:
                  type: string
                db-password:
                  type: string
                computed-values:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      expression:
                        type: string
                post-actions:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      expression:
                        type: string
                      