# istioPlatformNamespace: istio-system
pomeriumPlatform:
  pomerium:
    baseUrl: CHANGE_IT! qva-very-sit.aws.windtre.it
    proxy:
      authenticateServiceUrl: CHANGE_IT! https://auth-qva-very-sit.aws.windtre.it
    config:
      extraOpts:
        log_level: info
      insecure: true
      insecureProxy: true
      generateTLS: false
      generateSigningKey: true
      # rootDomain: CHANGE_IT! aws.windtre.it
      routes: |
        - from: https://kafka-ui-{{ .Values.baseUrl}}
          to: http://kafka-ui.platform.svc.cluster.local:8080
          timeout: 30s
          policy:
            - allow:
                and:
                  - authenticated_user: true
        - from: https://prometheus-{{ .Values.baseUrl}}
          to: http://monitoring-platform-kube-p-prometheus.platform.svc.cluster.local:9090
          timeout: 30s
          policy:
            - allow:
                and:
                  - authenticated_user: true
        - from: https://consul-ui-{{ .Values.baseUrl}}
          to: http://consul-platform-consul-ui.platform.svc.cluster.local:80
          timeout: 30s
          policy:
            - allow:
                and:
                  - authenticated_user: true
        {{ .Values.additionalRoutes}}
    authenticate:
      idp:
        provider: oidc
        url: CHANGE_IT! https://auth-qva-very-sit.aws.windtre.it/auth/realms/qvantel
        clientID: "pomerium"
        clientSecret: CHANGE_IT! "y158KQCP0fkxZCN3k4WVhwK5v5h347hX"
