apiVersion: v2
name: instana-platform
version: 0.0.1
dependencies:
  - name: instanaPlatform
    version: 0.0.1
annotations:
  images: |
    - name: agent-static
      image: icr.io/instana/agent:1.276.0
    - name: leader-elector
      image: icr.io/instana/leader-elector:0.5.19
    - name: k8sensor
      image: icr.io/instana/k8sensor:ffb74e9