instanaPlatform:
  instana-agent:
    enabled: true
    global:
      imageRegistry: "artifactory.qvantel.net"
      imagePullSecrets: []
      storageClass: ""
    agent:
      image:
        repository: artifactory.qvantel.net/instana/agent
#Agent key, endpoint host and port can be found in the Instana backend.
      key: to-be-filled
      endpointHost: to-be-filled
      endpointPort: 443
      env:
        INSTANA_AGENT_MODE: to-be-filled APM/INFRASTRCTURE
        INSTANA_AGENT_TAGS: to-be-filled
      pod:
        requests:
          cpu: 0.5
          memory: 512
        limits:
          memory: 768
      configuration_yaml: |
        com.instana.plugin.profiling.java:
          enabled: true
        com.instana.plugin.opentelemetry:
          enabled: true
        com.instana.ignore:
          processes:
            - 'stunnel'
          arguments:
            - 'io.strimzi.operator.cluster.Main'
            - 'kafka.Kafka'
            - 'org.apache.zookeeper.server.quorum.QuorumPeerMain'
            - 'io.strimzi.operator.topic.Main'
            - 'io.strimzi.operator.user.Main'
    cluster:
      name: to-be-filled
    zone:
      name: to-be-filled
  leaderElector:
    image:
      repository: artifactory.qvantel.net/instana/leader-elector
  k8s_sensor:
    image:
      repository: artifactory.qvantel.net/instana/k8sensor
    
