apiVersion: v2
name: aws-platform
version: 0.0.1
dependencies:
  - name: awsPlatform
    version: 0.0.1
annotations:
  images: |
    - name: aws-ebs-csi-driver
      image: public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.49.0
    - name: csi-provisioner
      image: public.ecr.aws/csi-components/csi-provisioner:v5.3.0-eksbuild.4
    - name: csi-attacher
      image: public.ecr.aws/csi-components/csi-attacher:v4.9.0-eksbuild.4
    - name: csi-snapshotter
      image: public.ecr.aws/csi-components/csi-snapshotter:v8.3.0-eksbuild.2
    - name: livenessprobe
      image: public.ecr.aws/csi-components/livenessprobe:v2.16.0-eksbuild.5
    - name: csi-resizer
      image: public.ecr.aws/csi-components/csi-resizer:v1.14.0-eksbuild.4
    - name: csi-node-driver-registrar
      image: public.ecr.aws/csi-components/csi-node-driver-registrar:v2.14.0-eksbuild.5
    - name: volume-modifier-for-k8s
      image: public.ecr.aws/ebs-csi-driver/volume-modifier-for-k8s:v0.8.0
    - name: aws-efs-csi-driver
      image: public.ecr.aws/efs-csi-driver/amazon/aws-efs-csi-driver:v2.1.12
    - name: aws-load-balancer-controller
      image: public.ecr.aws/eks/aws-load-balancer-controller:v2.13.4
    - name: init-udev-rule
      image: platform.artifactory.qvantel.net/platform/platform-k8s-tools-minimal:1.3.3_202509080945_master_90384dcc
    - name: dummy-container
      image: platform.artifactory.qvantel.net/platform/platform-k8s-tools-minimal:1.3.3_202509080945_master_90384dcc