apiVersion: v1
kind: Service
metadata:
  labels:
    cassandra.datastax.com/cluster: cassandra
    cassandra.datastax.com/datacenter: datacenter1
  annotations:
    consul.hashicorp.com/service-ports: native
  name: cassandra
  namespace: platform
spec:
  ports:
  - name: native
    port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    cassandra.datastax.com/cluster: cassandra
    cassandra.datastax.com/datacenter: datacenter1
  sessionAffinity: None
  type: ClusterIP
