{{- if $.Values.monitoringPlatform.qvantelMonitoring.programs.mmlyle }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: monitor-prometheus-order-managers-restarts.rules
  namespace: {{.Release.Namespace}}
  generation: 1
  annotations:
    meta.helm.sh/release-name: monitoring-platform
    meta.helm.sh/release-namespace: {{.Release.Namespace}}
  labels:
    app: kube-prometheus-stack
    release: monitoring-platform
spec:
  groups:
    - name: order-managers-restarts.alerts
      rules:
      - alert: OrdersManagerPodRestart
        expr: sum by (pod) (increase(kube_pod_container_status_restarts_total{container="orders-manager"}[1h]) >= 1)
        annotations:
          brief: 'Orders-manager has restarted, this is a critical component in LycaLebara and has direct impact to order handling'
          procedure: 'Check resource usage and logs if you can see anything obvious. In case this continues, escalate to L2 and on-call if needed. Alert created on QOPS-12116.'
        labels:
          severity: warning
      - alert: OrdersManagerPodRestartsInMinutes
        expr: sum by (pod) (increase(kube_pod_container_status_restarts_total{container="orders-manager"}[10m]) >= 2)
        annotations:
          brief: 'Orders-manager instances have restarted two or more times in 10 minutes, this is a critical component in LycaLebara and has direct impact to order handling'
          procedure: 'Check resource usage and logs if you can see anything obvious. Escalate to L2 and on-call if needed. Alert created on QOPS-12116.'
        labels:
          severity: critical
      - alert: OrdersManagerDeploymentRestartsInHour
        expr: sum(increase(kube_pod_container_status_restarts_total{container="orders-manager"}[1h])) >= 3
        annotations:
          brief: 'Orders-manager has had three or more restarts in an hour. This is a critical component in LycaLebara and has direct impact to order handling'
          procedure: 'Check resource usage and logs if you can see anything obvious. Escalate to L2 and on-call if needed. Alert created on QOPS-12116.'
        labels:
          severity: critical
      - alert: OrdersbatchManagerRestart
        expr: sum by (pod) (increase(kube_pod_container_status_restarts_total{container="orders-batch-manager"}[1h]) >= 1)
        annotations:
          brief: 'Orders-batch-manager has restarted, this is a critical component in LycaLebara and has direct impact to batch-order handling'
          procedure: 'Check resource usage and logs if you can see anything obvious. In case this continues, escalate to L2 of on-call if needed. Alert created on QOPS-12116.'
        labels:
          severity: warning
      - alert: OrdersBatchManagerPodRestartsInMinutes
        expr: sum by (pod) (increase(kube_pod_container_status_restarts_total{container="orders-batch-manager"}[10m]) >= 2)
        annotations:
          brief: 'Orders-batch-manager instances have restarted two or more times in 10 minutes, this is a critical component in LycaLebara and has direct impact to order handling'
          procedure: 'Check resource usage and logs if you can see anything obvious. Escalate to L2 and on-call if needed. Alert created on QOPS-12116.'
        labels:
          severity: critical
      - alert: OrdersBatchManagerDeploymentRestartsInHour
        expr: sum(increase(kube_pod_container_status_restarts_total{container="orders-batch-manager"}[1h])) >= 3
        annotations:
          brief: 'Orders-batch-manager has had three or more restarts in an hour. This is a critical component in LycaLebara and has direct impact to order handling'
          procedure: 'Check resource usage and logs if you can see anything obvious. Escalate to L2 and on-call if needed. Alert created on QOPS-12116.'
        labels:
          severity: critical
      - alert: OrdersBpmnExecRestart
        expr: sum by (pod) (increase(kube_pod_container_status_restarts_total{container="orders-bpmn-executor"}[1h]) >= 1)
        annotations:
          brief: 'Orders-bpmn-executor has restarted, this is a critical component in LycaLebara and has direct impact to order handling'
          procedure: 'Check resource usage and logs if you can see anything obvious. In case this continues, escalate to L2 and on-call if needed. Alert created on QOPS-12116.'
        labels:
          severity: warning
      - alert: OrdersBpmnExecDeploymentRestartsInMinutes
        expr: sum by (pod) (increase(kube_pod_container_status_restarts_total{container="orders-bpmn-executor"}[10m]) >= 2)
        annotations:
          brief: 'Orders-bpmn-executor instances have restarted two or more times in 10 minutes, this is a critical component in LycaLebara and has direct impact to order handling'
          procedure: 'Check resource usage and logs if you can see anything obvious. Escalate to L2 and on-call if needed. Alert created on QOPS-12116.'
        labels:
          severity: critical
      - alert: OrdersBpmnExecDeploymentRestartsInHour
        expr: sum(increase(kube_pod_container_status_restarts_total{container="orders-bpmn-executor"}[1h])) >= 3
        annotations:
          brief: 'Orders-bpmn-executor has had three or more restarts in an hour. This is a critical component in LycaLebara and has direct impact to order handling'
          procedure: 'Check resource usage and logs if you can see anything obvious. Escalate to L2 and on-call if needed. Alert created on QOPS-12116.'
        labels:
          severity: critical
      - alert: OrdersBatchBpmnExecRestart
        expr: sum by (pod) (increase(kube_pod_container_status_restarts_total{container="orders-batch-bpmn-executor"}[1h]) >= 1)
        annotations:
          brief: 'Orders-batch-bpmn-executor has restarted, this is a critical component in LycaLebara and has direct impact to order handling'
          procedure: 'Check resource usage and logs if you can see anything obvious. In case this continues, escalate to L2 of on-call if needed. Alert created on QOPS-12116.'
        labels:
          severity: warning
      - alert: OrdersBatchBpmnExecDeploymentRestartsInMinutes
        expr: sum by (pod) (increase(kube_pod_container_status_restarts_total{container="orders-batch-bpmn-executor"}[10m]) >= 2)
        annotations:
          brief: 'Orders-batch-bpmn-executor instances have restarted two or more times in 10 minutes, this is a critical component in LycaLebara and has direct impact to order handling'
          procedure: 'Check resource usage and logs if you can see anything obvious. Escalate to L2 and on-call if needed. Alert created on QOPS-12116.'
        labels:
          severity: critical
      - alert: OrdersBatchBpmnExecDeploymentRestartsInHour
        expr: sum(increase(kube_pod_container_status_restarts_total{container="orders-batch-bpmn-executor"}[1h])) >= 3
        annotations:
          brief: 'Orders-batch-bpmn-executor has had three or more restarts in an hour. This is a critical component in LycaLebara and has direct impact to order handling'
          procedure: 'Check resource usage and logs if you can see anything obvious. Escalate to L2 and on-call if needed. Alert created on QOPS-12116.'
        labels:
          severity: critical
{{- end }}