{{- if $.Values.monitoringPlatform.qvantelMonitoring.programs.mmlyle }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: monitor-prometheus-orders-bpmn-executor-throughput-monitoring.rules
  namespace: {{.Release.Namespace}}
  generation: 1
  annotations:
    meta.helm.sh/release-name: monitoring-platform
    meta.helm.sh/release-namespace: {{.Release.Namespace}}
  labels:
    app: kube-prometheus-stack
    release: monitoring-platform
spec:
  groups:
    - name: orders-bpmn-executor-throughput-monitoring.alerts
      rules:
      - alert: OrdersBpmnExecProcessesStartedBusinesshours
        expr: sum(rate(flex_bpmn_process_started_total{app=~"orders-bpmn-executor.*"}[5m])) > 70 unless ((hour() < 7 or hour() >19) or (day_of_week() > 5 or day_of_week() == 0))
        annotations:
          brief: 'This alert is looking for elevated load of the system during businesshours.'
          procedure: 'If this is actively alerting, follow the system functionality. System can deal with increased loads up to a certain point. Alert made on QOPS-12804.'
        labels:
          severity: warning
      - alert: OrdersBpmnExecProcessesStarted247
        expr: sum(rate(flex_bpmn_process_started_total{app=~"orders-bpmn-executor.*"}[5m])) > 200
        annotations:
          brief: This alert is looking for elevated load of the system around the clock.
          procedure: 'If this is actively alerting, follow the system functionality. System can deal with increased loads up to a certain point. Will likely alert during night time. Alert made on QOPS-12804.'
        labels:
          severity: warning
      - alert: OrdersBpmnExecProcessesCompletedWithErrorsAndEvent
        expr: sum(rate(flex_bpmn_process_completed_with_error_end_event_total{app=~"orders-bpmn-executor.*"}[5m])) > 10
        annotations:
          brief: 'This alert is following processes of OrdersBpmnExec with "error and event" finishes'
          procedure: 'This is around the clock alert. Should errors keep producing, escalate to L2 and on-call if needed. Alert made on QOPS-12804s'
        labels:
          severity: critical
      - alert: OrdersBpmnExecProcessesCompleted247
        expr: sum(rate(flex_bpmn_process_completed_total{app=~"orders-bpmn-executor.*"}[5m])) > 200
        annotations:
          brief: 'This alert is looking for elevated load around the clock.'
          procedure: 'If this is actively alerting, follow the system functionality. System can deal with increased loads up to a certain point. Will likely alert during night time. Alert made on QOPS-12804.'
        labels:
          severity: warning
      - alert: OrdersBpmnExecProcessesCompletedBusinesshours
        expr: sum(rate(flex_bpmn_process_completed_total{app=~"orders-bpmn-executor.*"}[5m])) > 100 unless ((hour() < 7 or hour() >19) or (day_of_week() > 5 or day_of_week() == 0))
        annotations:
          brief: 'This alert is looking for elevated load of the system during businesshours.'
          procedure: 'If this is actively alerting, follow the system functionality. System can deal with increased loads up to a certain point. Alert made on QOPS-12804.'
        labels:
          severity: warning
      - alert: OrdersBpmnExecProcessesCompletedWithTerminateAndEvent
        expr: sum(rate(flex_bpmn_process_completed_with_terminate_end_event_total{app=~"orders-bpmn-executor.*"}[5m])) > 2.5
        annotations:
          brief: 'This alert is following processes of OrdersBpmnExec with "terminate and event" finishes'
          procedure: 'This is around the clock alert. Should errors keep producing, escalate to L2 and on-call if needed. Alert made on QOPS-12804.'
        labels:
          severity: critical
      - alert: OrdersBpmnExecProcessesCancelled
        expr: sum(rate(flex_bpmn_process_cancelled_total{app=~"orders-bpmn-executor.*"}[10m])) > 0.008
        annotations:
          brief: 'This alert is watching for processes with "cancelled" status. This should be quite low profile metric'
          procedure: 'If large amounts of orders are being actively cancelled, escalate to L2 and on-call in needed. Alert made on QOPS-12804.'
        labels:
          severity: critical
      - alert: OrdersBpmnExecProcessesInTriggerableService
        expr: sum(rate(flex_bpmn_process_in_triggerable_service_task_entered_total{app=~"orders-bpmn-executor.*"}[5m])) - sum(rate(flex_bpmn_process_in_triggerable_service_task_exited_total{app=~"orders-bpmn-executor.*"}[5m])) > 12
        annotations:
          brief: 'This alert is looking for processes waiting in "triggerable service".'
          procedure: 'If large amounts of processes are waiting, that means something isnt functioning properly. Escalate to L2 if processes keep accumulating and on-call if needed. Alert made on QOPS-12804.'
        labels:
          severity: critical
{{- end }}