{{- if $.Values.monitoringPlatform.qvantelMonitoring.programs.mmlyle }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: monitor-balance-adjustments.rules
  namespace: {{.Release.Namespace}}
  generation: 1
  annotations:
    meta.helm.sh/release-name: monitoring-platform
    meta.helm.sh/release-namespace: {{.Release.Namespace}}
  labels:
    app: kube-prometheus-stack
    release: monitoring-platform
spec:
  groups:
    - name: balance-adjustments-errors.alerts
      rules:
      - alert: MainMonetaryBalanceErrorRate
        expr: (round(sum(increase(flex_bpmn_activity_error_received_total{app!="",definition="adjust-balance"}[20m])))/((round(sum(increase(flex_bpmn_activity_error_received_total{app!="",definition="adjust-balance"}[20m])))) + round(sum(increase(flex_bpmn_activity_completed_total{app!="",definition="adjust-balance"}[20m]))))) * 100 > 10 unless ((hour() < 7 or hour() >19) or (day_of_week() > 5 or day_of_week() == 0))
        annotations:
          brief: Only applicable during business hours. There are more than 10% errors in adjust-balance, it indicates that there might be problems in Balance adjustments. This is only used in SCT so no critical impact.
          procedure: Creation ticket https://qvantel.atlassian.net/browse/QOPS-11563 . Check the graphs from prometheus and raise an SL3 ticket if the errors continue for a while.
        labels:
          severity: warning
      - alert: AllowanceBalanceErrorRate
        expr: (round(sum(increase(flex_bpmn_activity_error_received_total{app!="",definition="care-manage_balance_allowance-adjust_allowance_balance"}[20m])))/((round(sum(increase(flex_bpmn_activity_error_received_total{app!="",definition="care-manage_balance_allowance-adjust_allowance_balance"}[20m])))) + round(sum(increase(flex_bpmn_activity_completed_total{app!="",definition="care-manage_balance_allowance-adjust_allowance_balance"}[20m]))))) * 100 > 10 unless ((hour() < 7 or hour() >19) or (day_of_week() > 5 or day_of_week() == 0))
        annotations:
          brief: Only applicable during business hours. There are more than 10% errors in care-manage_balance_allowance-adjust_allowance_balance, it indicates that there might be problems in Balance adjustments. This is only used in SCT so no critical impact.
          procedure: Creation ticket https://qvantel.atlassian.net/browse/QOPS-11563 . Check the graphs from prometheus and raise an SL3 ticket if the errors continue for a while.
        labels:
          severity: warning
      - alert: MonetaryBalancesChildProcessErrorRate
        expr: (round(sum(increase(flex_bpmn_activity_error_received_total{app!="",definition="execute-balance-adjustment-in-charging-system"}[20m])))/((round(sum(increase(flex_bpmn_activity_error_received_total{app!="",definition="execute-balance-adjustment-in-charging-system"}[20m])))) + round(sum(increase(flex_bpmn_activity_completed_total{app!="",definition="execute-balance-adjustment-in-charging-system"}[20m]))))) * 100 > 10 unless ((hour() < 7 or hour() >19) or (day_of_week() > 5 or day_of_week() == 0))
        annotations:
          brief: 'Only applicable during business hours. If there are more than 10% errors in execute-balance-adjustment-in-charging-system, it indicates that there might be problems in Balance adjustments. This is only used in SCT so no critical impact.'
          procedure: 'Creation ticket https://qvantel.atlassian.net/browse/QOPS-11563 . Check the graphs from prometheus and raise an SL3 ticket if the errors continue for a while.'
        labels:
          severity: warning
{{- end }}