apiVersion: v2
name: mariadb-operator-platform
version: 0.0.1
dependencies:
  - name: mariadbOperatorPlatform
    version: 0.0.1
annotations:
  images: |
    - name: mariadb-operator
      image: platform-artifactory.qvantel.net/mariadb-operator/mariadb-operator:v0.0.28
    - name: mariadb
      image: platform-artifactory.qvantel.net/library/mariadb:10.4.33
