apiVersion: v2
name: mariadb-operator-platform
version: 0.0.1
dependencies:
  - name: mariadbOperatorPlatform
    version: 0.0.1
annotations:
  images: |
    - name: mariadb-operator
      image: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator:v0.0.30
    - name: mariadb
      image: docker.io/mariadb:10.6.19
    - name: maxscale
      image: docker-registry2.mariadb.com/mariadb/maxscale:23.08.5
    - name: mariadb-exporter
      image: prom/mysqld-exporter:v0.15.1
    - name: maxscale-exporter
      image: docker-registry2.mariadb.com/mariadb/maxscale-prometheus-exporter-ubi:v0.0.1
    
