apiVersion: v2
name: mariadb-operator-platform
version: 0.0.1
dependencies:
- name: mariadbOperatorPlatform
  version: 0.0.1
annotations:
  images: |
    - name: mariadb-operator
      image: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator:25.10.1
    - name: mariadb-10-6
      image: docker.io/mariadb:10.6.19
    - name: mariadb-10-11
      image: docker.io/mariadb:10.11.9
    - name: mariadb-11-4
      image: docker.io/mariadb:11.4.3
    - name: maxscale
      image: docker-registry2.mariadb.com/mariadb/maxscale:23.08.5
    - name: mariadb-exporter
      image: prom/mysqld-exporter:v0.15.1
    - name: maxscale-exporter
      image: docker-registry2.mariadb.com/mariadb/maxscale-prometheus-exporter-ubi:v0.0.1
