mariadbOperatorPlatform:
  nameOverride: "mariadb-operator-platform"
  webhook:
    cert:
      certManager:
        enabled: true
  metrics:
    enabled: true
  clusters:
    mariadb:
      enabled: true
      vaultConfiguration: true
      spec:
        storage:
          size: 10Gi
        replicas: 2
        replication:
          enabled: true
        metrics:
          enabled: true
        affinity:
          enableAntiAffinity: true
        tolerations:
          - key: "k8s.mariadb.com/ha"
            operator: "Exists"
            effect: "NoSchedule"
        podDisruptionBudget:
          maxUnavailable: 33%
        updateStrategy:
          type: RollingUpdate
        myCnf: |
          [mariadb]
          bind-address=*
          default_storage_engine=InnoDB
          binlog_format=row
          innodb_autoinc_lock_mode=2
          max_allowed_packet=256M
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 1Gi
