apiVersion: v2
name: vaultPlatform
version: 0.0.1
dependencies:
  - name: vault-secrets-webhook
    version: 1.20.0
    repository: https://kubernetes-charts.banzaicloud.com
    condition: vaultWebhooksEnabled
  - name: vault
    version: 0.23.0
    repository: https://helm.releases.hashicorp.com