apiVersion: v2
name: kasope-platform
version: 0.0.1
dependencies:
- name: kasopePlatform
  version: 0.0.1
annotations:
  images: |
    - name: cass-operator
      image: docker.io/k8ssandra/cass-operator:v1.27.1
    - name: cassandra
      image: docker.io/k8ssandra/cass-management-api:3.11.13
    - name: cassandra
      image: docker.io/k8ssandra/cass-management-api:4.1.8-ubi8
    - name: systemLogger
      image: docker.io/k8ssandra/system-logger:v1.27.1
    - name: configBuilder
      image: docker.io/datastax/cass-config-builder:1.0-ubi8
    - name: per-node-config
      image: platform.artifactory.qvantel.net/platform/platform-k8s-tools-minimal:1.3.3_202509080945_master_90384dcc
    - name: k8ssandraClient
      image: docker.io/k8ssandra/k8ssandra-client:v0.8.3
    - name: k8ssandra-operator
      image: docker.io/k8ssandra/k8ssandra-operator:v1.27.0
    - name: reaper
      image: thelastpickle/cassandra-reaper:4.0.0
    - name: medusa
      image: docker.io/k8ssandra/medusa:0.25.1
    - name: kubectl
      image: platform.artifactory.qvantel.net/platform/platform-k8s-tools-minimal:1.3.3_202509080945_master_90384dcc
