kasopePlatform:
  k8ssandra-operator:
    cass-operator:
      admissionWebhooks:
        enabled: false
  clusters:
    - name: cluster
      spec:
        cassandra:
          serverVersion: "3.11.13"
          metadata:
            services:
              dcService:
                annotations:
                  consul.hashicorp.com/service-port: native
              allPodsService:
                annotations:
                  consul.hashicorp.com/service-port: native
          config:
            cassandraYaml:
              num_tokens: 8
            jvmOptions:
              heapSize: 4Gi
          storageConfig:
            cassandraDataVolumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 100Gi
          resources:
            requests:
              memory: 8Gi
          datacenters:
            - metadata:
                name: dc1
                services:
                  dcService:
                    annotations:
                      consul.hashicorp.com/service-port: native
                  allPodsService:
                    annotations:
                      consul.hashicorp.com/service-port: native
              size: 3
          telemetry:
            prometheus:
              enabled: true
              commonLabels:
                release: monitoring-platform
            mcac:
              enabled: false
        reaper:
          autoScheduling:
            enabled: true
