kasopePlatform:
  k8ssandra-operator:
    cass-operator:
      admissionWebhooks:
        enabled: false
  clusters:
    - name: cluster
      spec:
        cassandra:
          serverVersion: "3.11.11"
          config:
            cassandraYaml:     
              num_tokens: 8
            jvmOptions:
              heapSize: 4Gi
          storageConfig:
            cassandraDataVolumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 100Gi
          resources:
            requests:
              memory: 8Gi
          datacenters:
            - metadata:
                name: dc1
                services:
                  dcService:
                    annotations:
                      consul.hashicorp.com/service-port: native
              size: 3
          telemetry:
            prometheus:
              enabled: true
        reaper:
          autoScheduling:
            enabled: true