apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftpgo-pvc
  namespace: platform
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi