apiVersion: v2
name: monitoring-platform
version: 0.0.1
dependencies:
  - name: monitoringPlatform
    version: 0.0.1
annotations:
  images: |
    - name: x509-certificate-exporter
      image: docker.io/enix/x509-certificate-exporter:3.14.0
    - name: prometheus-blackbox-exporter
      image: quay.io/prometheus/blackbox-exporter:v0.25.0
    - name: prometheus-consul-exporter
      image: prom/consul-exporter:v0.5.0
    - name: yet-another-cloudwatch-exporter
      image: ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.61.2
    - name: alertmanager
      image: quay.io/prometheus/alertmanager:v0.27.0
    - name: prometheus-operator-webhook
      image: quay.io/prometheus-operator/admission-webhook:v0.77.1
    - name: admissionWebhooks
      image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6
    - name: prometheus-operator
      image: quay.io/prometheus-operator/prometheus-operator:v0.77.1
    - name: prometheusConfigReloader
      image: quay.io/prometheus-operator/prometheus-config-reloader:v0.77.1
    - name: thanos
      image: quay.io/thanos/thanos:v0.36.1
    - name: prometheus
      image: quay.io/prometheus/prometheus:v2.54.1
    - name: thanos-rules
      image: quay.io/thanos/thanos:v0.36.1
    - name: grafana
      image: docker.io/grafana/grafana-enterprise:11.2.1
    - name: testFramework
      image: docker.io/bats/bats:v1.4.1
    - name: downloadDashboardsImage
      image: docker.io/curlimages/curl:7.85.0
    - name: initChownData
      image: registry.access.redhat.com/ubi9/ubi-minimal:9.4-1194
    - name: grafana-sidecar
      image: quay.io/kiwigrid/k8s-sidecar:1.27.4
    - name: imageRenderer
      image: docker.io/grafana/grafana-image-renderer:3.11.5
    - name: prometheus-node-exporter
      image: quay.io/prometheus/node-exporter:v1.8.2
    - name: kubeRBACProxy
      image: quay.io/brancz/kube-rbac-proxy:v0.18.0
    - name: kube-state-metrics
      image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.13.0
    - name: grafana-plugins
      image: platform.artifactory.qvantel.net/platform/grafana-plugins:1.2.0_4_f26bb6e90
    - name: alloy
      image: grafana/alloy:v1.5.0
    - name: configmap-reload
      image: ghcr.io/jimmidyson/configmap-reload:v0.12.0
    - name: beyla
      image: grafana/beyla:1.9.0
    - name: beyla-k8s-cache
      image: grafana/beyla-k8s-cache:1.9.0
    - name: tempo
      image: docker.io/grafana/tempo:2.6.0
    - name: queryFrontendQuery
      image: grafana/tempo-query:2.6.0
    - name: memcached
      image: docker.io/memcached:1.6.33-alpine
    - name: memcachedExporter
      image: prom/memcached-exporter:v0.14.4
    - name: gateway
      image: nginxinc/nginx-unprivileged:1.27-alpine
    - name: enterprise
      image: grafana/enterprise-traces:v2.6.1

