apiVersion: v2
name: monitoring-platform
version: 0.0.1
dependencies:
  - name: monitoringPlatform
    version: 0.0.1
annotations:
  images: |
    - name: x509-certificate-exporter
      image: docker.io/enix/x509-certificate-exporter:3.19.0
    - name: prometheus-blackbox-exporter
      image: quay.io/prometheus/blackbox-exporter:v0.27.0
    - name: prometheus-consul-exporter
      image: prom/consul-exporter:v0.5.0
    - name: yet-another-cloudwatch-exporter
      image: ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.61.2
    - name: alertmanager
      image: quay.io/prometheus/alertmanager:v0.28.1
    - name: prometheus-operator-webhook
      image: quay.io/prometheus-operator/admission-webhook:v0.85.0
    - name: admissionWebhooks
      image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.6.2
    - name: prometheus-operator
      image: quay.io/prometheus-operator/prometheus-operator:v0.85.0
    - name: prometheusConfigReloader
      image: quay.io/prometheus-operator/prometheus-config-reloader:v0.85.0
    - name: thanos
      image: quay.io/thanos/thanos:v0.39.2
    - name: prometheus
      image: quay.io/prometheus/prometheus:v3.5.0
    - name: thanos-rules
      image: quay.io/thanos/thanos:v0.39.2
    - name: grafana
      image: docker.io/grafana/grafana-enterprise:12.2.2
    - name: initChownData
      image: platform.artifactory.qvantel.net/platform/platform-k8s-tools-minimal:1.3.3_202509080945_master_90384dcc
    - name: grafana-sidecar
      image: quay.io/kiwigrid/k8s-sidecar:1.30.10
    - name: imageRenderer
      image: docker.io/grafana/grafana-image-renderer:v4.0.17
    - name: prometheus-node-exporter
      image: quay.io/prometheus/node-exporter:v1.9.1
    - name: kubeRBACProxy
      image: quay.io/brancz/kube-rbac-proxy:v0.19.1
    - name: kube-state-metrics
      image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.17.0
    - name: grafana-plugins
      image: platform.artifactory.qvantel.net/platform/grafana-plugins:1.2.0_8_b278cb9c4
    - name: alloy
      image: grafana/alloy:v1.10.1
    - name: prometheusConfigReloader
      image: quay.io/prometheus-operator/prometheus-config-reloader:v0.81.0
    - name: configmap-reload
      image: ghcr.io/jimmidyson/configmap-reload:v0.14.0
    - name: beyla
      image: grafana/beyla:1.9.8
    - name: beyla-k8s-cache
      image: grafana/beyla-k8s-cache:1.9.8
    - name: tempo
      image: docker.io/grafana/tempo:2.8.2
    - name: queryFrontendQuery
      image: grafana/tempo-query:2.8.2
    - name: memcached
      image: docker.io/library/memcached:1.6.33-alpine
    - name: memcachedExporter
      image: prom/memcached-exporter:v0.14.4
    - name: gateway
      image: nginxinc/nginx-unprivileged:1.27-alpine
    - name: enterprise
      image: grafana/enterprise-traces:v2.8.1
