redisPcdPlatform:
  redis:
    global:
      redis:
        password: "test"
    fullnameOverride: "redis-cluster-redis-pcd"
    image:
      repository: bitnami/redis
      tag: 6.2.7-debian-10-r0
      pullPolicy: IfNotPresent

    architecture: replication
    auth:
      enabled: true
      sentinel: true
      password: "test"

    master:
      configuration: ""
      disableCommands:
        - FLUSHDB
        - FLUSHALL
      containerPorts:
        redis: 6379
      resources:
        limits: {}
        requests: {}
      kind: StatefulSet
      metadata:
        namespace: platform
      podAntiAffinityPreset: soft
      persistence:
        enabled: true
        path: /data
        accessModes:
          - ReadWriteOnce
        size: 8Gi
      service:
        type: ClusterIP
        ports:
          redis: 6379
        nodePorts:
          redis: ""
        externalTrafficPolicy: Cluster
        internalTrafficPolicy: Cluster

    replica:
      replicaCount: 3
      configuration: ""
      disableCommands:
        - FLUSHDB
        - FLUSHALL
      externalMaster:
        enabled: false
        host: ""
        port: 6379
      containerPorts:
        redis: 6379
      resources:
        limits: {}
        requests: {}
      podAntiAffinityPreset: soft
      persistence:
        enabled: true
        path: /data
        accessModes:
          - ReadWriteOnce
        size: 8Gi
      service:
        type: ClusterIP
        ports:
          redis: 6379
        nodePorts:
          redis: ""
        externalTrafficPolicy: Cluster
        internalTrafficPolicy: Cluster

    sentinel:
      enabled: true
      image:
        repository: bitnami/redis-sentinel
        tag: 6.2.7-debian-10-r0
        pullPolicy: IfNotPresent
        pullSecrets: []
        debug: false
      masterSet: mymaster
      quorum: 2
      externalMaster:
        enabled: false
        host: ""
        port: 6379
      containerPorts:
        sentinel: 26379
      persistence:
        accessModes:
          - ReadWriteOnce
        size: 100Mi
      service:
        type: ClusterIP
        ports:
          redis: 6379
          sentinel: 26379
    networkPolicy:
      enabled: false
      allowExternal: true
      extraIngress: []
      extraEgress: []
      ingressNSMatchLabels: {}
      ingressNSPodMatchLabels: {}

    metrics:
      enabled: false
      image:
        repository: bitnami/redis-exporter
        tag: 1.37.0-debian-10-r39
        pullPolicy: IfNotPresent
      resources:
        limits: {}
        requests: {}
      podLabels: {}
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
      service:
        type: ClusterIP
        port: 9121
        externalTrafficPolicy: Cluster
        extraPorts: []
        loadBalancerIP: ""
        loadBalancerSourceRanges: []
        annotations: {}