{{- if .Values.mariaOperatorPlatform.clusters }}
{{- range keys .Values.mariaOperatorPlatform.clusters  }}
{{- $current := get $.Values.mariaOperatorPlatform.clusters . }}
{{- if $current.enabled }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ . }}
  namespace: platform
spec:
  {{- toYaml $current.spec | nindent 2 }}

{{- end }}
{{- end }}
{{- end }}