apiVersion: platform.qvantel.com/v1
kind: VaultDbRole
metadata:
  name: mysql-orders-manager
  namespace: platform
spec:
  creation-statement: "CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}'; GRANT ALL PRIVILEGES ON scheduled_orders.* TO '{{name}}'@'%' WITH GRANT OPTION;"  
  db-name: x-aurora-mysql-database
  default-ttl: 1h
  max-ttl: 24h
  role-name: mysql_orders-manager