{{- if $.Values.monitoringPlatform.qvantelMonitoring.applications.commonOnePointZero }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{.Release.Name}}-containers.rules
  namespace: {{.Release.Namespace}}
  generation: 1
  annotations:
    meta.helm.sh/release-name: {{.Release.Name}}
    meta.helm.sh/release-namespace: {{.Release.Namespace}}
  labels:
    app: kube-prometheus-stack
    release: {{.Release.Name}}
spec:
  groups:
  - name: container.alerts
    rules:
    - alert: TemporaryContainerRunning
      annotations:
        brief: "A temporary container with the name {{` {{ $labels.container }} `}} has been running for {{` {{ $value|humanizeDuration }} `}} on pod {{` {{ $labels.pod }} `}}. Since it's a temporary container and it's been running for this long, it's very likely that someone forgot to stop it and in that case, it would be wasting resources."
        procedure: "If a username is present in \"{{` {{ $labels.container }} `}}\", reach out to them and ask if they are still using it. If there isn't a username in the container name nor a warning asking people to not stop it, stop the container with \"docker stop {{` {{ $labels.name }} `}}\""
      expr: (time() - container_start_time_seconds{name=~"(exciting|strange|busy|beautiful|nice|intelligent|funny|interesting|great|admiring|adoring|affectionate|agitated|amazing|angry|awesome|blissful|bold|boring|brave|charming|clever|cocky|cool|compassionate|competent|condescending|confident|cranky|crazy|dazzling|determined|distracted|dreamy|eager|ecstatic|elastic|elated|elegant|eloquent|epic|fervent|festive|flamboyant|focused|friendly|frosty|gallant|gifted|goofy|gracious|happy|hardcore|heuristic|hopeful|hungry|infallible|inspiring|jolly|jovial|keen|kind|laughing|loving|lucid|magical|mystifying|modest|musing|naughty|nervous|nifty|nostalgic|objective|optimistic|peaceful|pedantic|pensive|practical|priceless|quirky|quizzical|recursing|relaxed|reverent|romantic|sad|serene|sharp|silly|sleepy|stoic|stupefied|suspicious|sweet|tender|thirsty|trusting|unruffled|upbeat|vibrant|vigilant|vigorous|wizardly|wonderful|xenodochial|youthful|zealous|zen)_.+|.*nodetool.*|.*cqlsh.*|.*tools.*|.*-cli.*|.*impala.*shell.*|.*drolex.*|.*tibemsadmin.*|.*mysql-.*|.*robot.*docker.*test.*|keytool-.*", image!~"(.*exporter.*)" }) > 3600
      for: 5m
      labels:
        level: application
        severity: info
    - alert: AppOccasionalDeaths
      annotations:
        brief: "{{` {{ $value }} `}} {{` {{ $labels.container }} `}} on pod {{` {{ $labels.pod }} `}} instances have died in the last 1h, this behaviour could be affecting service availability."
        escalation: "Escalate to L2 following the established procedure and taking into account the severity of this alert (warning)."
      expr: 3 <= sum by (container, pod, namespace) (clamp_max(label_replace(time() - max_over_time(container_last_seen{pod!~"(cp_.+|.*dump.*)"}[1h]) > 120, "container", "$1", "container", "([^\\.]+).*"), 1))
      labels:
        level: application
        severity: warning
    - alert: AppFrequentDeaths
      annotations:
        brief: "{{` {{ $value }} `}} {{` {{ $labels.container }} `}} on pod {{` {{ $labels.pod }} `}} instances have died in the last 10m (it's a bloodbath!), this behaviour could be affecting service availability."
        escalation: "Escalate to L2 following the established procedure and taking into account the severity of this alert (critical)."
      expr: 3 <= sum by (container, pod, namespace) (clamp_max(label_replace(time() - max_over_time(container_last_seen{pod!~"(cp_.+|.*dump.*)"}[10m]) > 120, "container", "$1", "container", "([^\\.]+).*"), 1))
      labels:
        level: application
        severity: critical
    - alert: ContainerHighMemoryUsage
      annotations:
        brief: "The {{` {{ $labels.container }} `}} container on pod {{` {{ $labels.pod }} `}} is using {{` {{ $value|humanize }} `}}% of the memory assigned to it. This means that the container could be close to running out of memory which could mean outage or degradation of the service that it's providing."
        procedure: "Check that the {{` {{ $labels.container }} `}} container on node {{` {{ $labels.node }} `}} is not a temporary container and check if it is crashing. If it's not a temporary container and it is crashing, then escalate to L2 so they can investigate it as soon as possible. If it isn't crashing but it's not a temporary container, treat this as a warning and escalate to L2 for investigation during business hours."
      expr: container_memory_rss{image!~"(.*docker-ems-tools.*|.*docker-cassandra-tools.*|.*kafkacat.*|.*drolex.*)", name!~"(exciting|strange|busy|beautiful|nice|intelligent|funny|interesting|great|admiring|adoring|affectionate|agitated|amazing|angry|awesome|blissful|bold|boring|brave|charming|clever|cocky|cool|compassionate|competent|condescending|confident|cranky|crazy|dazzling|determined|distracted|dreamy|eager|ecstatic|elastic|elated|elegant|eloquent|epic|fervent|festive|flamboyant|focused|friendly|frosty|gallant|gifted|goofy|gracious|happy|hardcore|heuristic|hopeful|hungry|infallible|inspiring|jolly|jovial|keen|kind|laughing|loving|lucid|magical|mystifying|modest|musing|naughty|nervous|nifty|nostalgic|objective|optimistic|peaceful|pedantic|pensive|practical|priceless|quirky|quizzical|recursing|relaxed|reverent|romantic|sad|serene|sharp|silly|sleepy|stoic|stupefied|suspicious|sweet|tender|thirsty|trusting|unruffled|upbeat|vibrant|vigilant|vigorous|wizardly|wonderful|xenodochial|youthful|zealous|zen)_.+|^kafka-tools.+|.*-cli.*|^impala-shell.*|.*mysql.*|.*robot.*docker.*test.*|keytool-.*"} / container_spec_memory_limit_bytes * 100 >= 95 and container_spec_memory_limit_bytes != 0
      for: 5m
      labels:
        level: application
        severity: warning
    - alert: ContainerOomKilled
      annotations:
        brief: "The {{` {{ $labels.container }} `}} container on pod {{` {{ $labels.pod }} `}} has been oomkilled {{` {{ $value|humanize }} `}} times within the last hour." 
        procedure: "Consider if this warning alert could have service impact and escalate following the established procedure."
      expr: sum by (namespace,pod,container) (increase(kube_pod_container_status_restarts_total[1h])) * on(namespace,pod,container) group_left(reason) kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} >= 1 <=3
      for: 5m
      labels:
        level: application
        severity: warning
    - alert: ContainerOomKilledFrequently
      annotations:
        brief: "The {{` {{ $labels.container }} `}} container on pod {{` {{ $labels.pod }} `}} has been oomkilled {{` {{ $value|humanize }} `}} times within the last hour." 
        procedure: "The {{` {{$labels.container}} `}} has been OOMkilled frequently. Depending on the component, this should likely be addressed asap. Escalate following the established procedure."
      expr: sum by (namespace,pod,container) (increase(kube_pod_container_status_restarts_total[1h])) * on(namespace,pod,container) group_left(reason) kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} >= 4
      for: 5m
      labels:
        level: application
        severity: critical
{{- end }}
