apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{.Release.Name}}-prometheus-custom-alerting.rules
  namespace: {{.Release.Namespace}}
  generation: 1
  annotations:
    meta.helm.sh/release-name: {{.Release.Name}}
    meta.helm.sh/release-namespace: {{.Release.Namespace}}
  labels:
    app: kube-prometheus-stack
    release: {{.Release.Name}}
spec:
  groups:
  - name: prometheus.custom.alerts
    rules:
    - alert: PrometheusMetricsAppendedHigh
      expr: rate(prometheus_tsdb_head_samples_appended_total[5m]) > 150000
      for: 10m
      labels:
        severity: critical
        level: application
      annotations:
        brief: "Amount of metrics being appended to Prometheus is high"
        procedure: "Please escalate to monitoring team for a checkup."
{{- if $.Values.monitoringPlatform.qvantelMonitoring.integrations.opsgenie }}
  - name: deadmans-switch.alerts
    rules:
    - alert: DeadMansSwitch
      expr: vector(1)
      labels:
        severity: none
        level: application
      annotations:
        brief: This DeadMansSwitch alert is used to ensure that the alerting pipeline is functional. This is supposed to alert constantly in Prometheus and Alertmanager will send a heartbeat to Opsgenie.
        escalation: Qvantel Operations Center and Platform teams are automatically informed via e-mail from Opsgenie if the Opsgenie heartbeat dies.
{{- end }}