{{- if .Values.certPlatform.clusterIssuers }}
{{- range keys .Values.certPlatform.clusterIssuers  }}
{{- $current := get $.Values.certPlatform.clusterIssuers . }}
{{- if $current.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ . }}
  namespace: {{.Release.Namespace}}
spec:
  {{- print "\n" ($current.spec | toYaml | indent 2) }}

{{- end }}
{{- end }}
{{- end }}