---
{{- $secret := (randAscii 32) }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace "rabbitmq-erlang-secret").data }}
{{- if $secretData }}
{{- $secret = (index $secretData "rabbitmq-erlang-cookie" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "rabbitmq-erlang-secret"
type: Opaque
data:
  rabbitmq-erlang-cookie: {{ $secret | b64enc }}