---
{{- $secret := (randAscii 32 | b64enc) }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace "grafana-keycloak-client-secret").data }}
{{- if $secretData }}
{{- $secret = (index $secretData "GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "grafana-keycloak-client-secret"
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: {{ $secret | b64enc }}