---
{{- $password := (randAscii 32 | b64enc) }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace "grafana-admin-pass-secret").data }}
{{- if $secretData }}
{{- $password = (index $secretData "grafanaAdminPassword" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "grafana-admin-pass-secret"
type: Opaque
data:
  adminUser: {{ "admin" | b64enc }}
  grafanaAdminPassword: {{ $password | b64enc }}