apiVersion: v1
kind: Secret
metadata:
  name: "grafana-keycloak-client-secret"
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ZDZlOGJjMTctNDI4OS00MmY1LWI4N2QtZGI4OWVlYmIyMmEx