## Needed for Grafana to access Logsearch datasource in operator namespace.
---
{{- if eq .Values.global.deployOperators "false" }}
{{- $configMap := (lookup "v1" "ConfigMap" .Values.global.operatorNamespace "addon-operator") }}
{{- if $configMap }}
{{- $elasticsearchPlatformEnabled := (index $configMap.data.elasticsearchPlatformEnabled) }}
{{- if eq $elasticsearchPlatformEnabled "true" }}
{{- $secret := (randAscii 32 | b64enc) }}
{{- $secretData := (lookup "v1" "Secret" .Values.global.operatorNamespace "logsearch-es-elastic-user").data }}
{{- if $secretData }}
{{- $secret = (index $secretData "elastic" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "logsearch-es-elastic-user"
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  elastic: {{ $secret | b64enc }}
{{- end }}
{{- end }}
{{- end }}