apiVersion: v2
name: istioPlatform
version: 0.0.1
dependencies:
  - name: base
    version: "1.23.2"
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istiod.enabled
  - name: istiod
    version: "1.23.2"
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istiod.enabled