externalDns:
  awsRole: ""
  awsAssumeRole: ""
  route53ZonId: ""
  annotationFilter: platform.qvantel.com/exclude-from-external-dns notin (true)
  pollInterval: "10m"
  dryRun: "1"
  logLevel: "debug"