apiVersion: v2
name: vault-platform
version: 0.0.1
dependencies:
  - name: vaultPlatform
    version: 0.0.1
annotations:
  images: |
    - name: vault
      image: docker.io/hashicorp/vault:1.12.1
    - name: vault-secrets-webhook
      image: ghcr.io/banzaicloud/vault-secrets-webhook:1.18.0
    - name: vault-env
      image: ghcr.io/banzaicloud/vault-env:1.18.0
    - name: platform-tools
      image: platform.artifactory.qvantel.net/platform/platform-k8s-tools-minimal:1.2.0_10_5193dbce5