{{- if index $.Values "monitoringPlatform" "yet-another-cloudwatch-exporter" "enabled" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{.Release.Name}}-kube-p-aws-rds.rules
  namespace: {{.Release.Namespace}}
  generation: 1
  annotations:
    meta.helm.sh/release-name: {{.Release.Name}}
    meta.helm.sh/release-namespace: {{.Release.Namespace}}
  labels:
    app: kube-prometheus-stack
    release: {{.Release.Name}}
spec:
  groups:
  - name: AWS-RDS
    rules:
    - alert: LongCPUThrottling
      expr: |
        aws_rds_cpuutilization_average > 95
      for: 10m
      labels:
        severity: critical
      annotations:
        brief: CPU over 95% for 10 minutes in instance {{` {{$labels.dimension_DBInstanceIdentifier}} `}}
        procedure: "Contact SQL urgently to verify the potential risk and create a ticket to them"
    - alert: LowFreeMemory
      expr: |
        aws_rds_freeable_memory_average < 128*1024*1024
      for: 10m
      labels:
        severity: critical
      annotations:
        brief: Free memory under 128MB in instance {{` {{$labels.dimension_DBInstanceIdentifier}} `}}
        procedure: "Contact SQL urgently to verify the potential risk and create a ticket to them"
    - alert: LowFreeDisk
      expr: |
        aws_rds_free_storage_space_average < 512*1024*1024
      for: 10m
      labels:
        severity: critical
      annotations:
        brief: Free disk under 512MB {{` {{$labels.dimension_DBInstanceIdentifier}} `}}
        procedure: "Contact SQL urgently to verify the potential risk and create a ticket to them"
    - alert: DiskFullIn48H
      expr: |
        predict_linear(aws_rds_free_storage_space_average[48h], 48 * 3600) < 0
      for: 10m
      labels:
        severity: warning
      annotations:
        brief: Disk will be full within 48 hours in instance {{` {{$labels.dimension_DBInstanceIdentifier}} `}}
        procedure: "Contact SQL team during business hours over a ticket"
    - alert: DiskFullIn12H
      expr: |
        predict_linear(aws_rds_free_storage_space_average[12h], 12 * 3600) < 0
      for: 10m
      labels:
        severity: critical
      annotations:
        brief: Disk will be full within 12 hours in instance {{` {{$labels.dimension_DBInstanceIdentifier}} `}}
        procedure: "Contact SQL team during business hours over a ticket"
    - alert: HighReadLatency
      expr: |
        aws_rds_read_latency_average > 0.250
      for: 10m
      labels:
        severity: warning
      annotations:
        brief: Average read latency over 250ms in instance {{` {{$labels.dimension_DBInstanceIdentifier}} `}}
        procedure: "Contact SQL team during business hours over a ticket"
    - alert: HighWriteLatency
      expr: |
        aws_rds_write_latency_average > 0.250
      for: 10m
      labels:
        severity: warning
      annotations:
        brief: Average write latency over 250ms in instance {{` {{$labels.dimension_DBInstanceIdentifier}} `}}
        procedure: "Contact SQL team during business hours over a ticket"
    - alert: HighDiskQueue
      expr: |
        aws_rds_disk_queue_depth_average > 25
      for: 10m
      labels:
        severity: warning
      annotations:
        brief: High disk queue depth in instance {{` {{$labels.dimension_DBInstanceIdentifier}} `}}
        procedure: "Contact SQL team during business hours over a ticket"
{{- end }}