logsearchPlatform:
  # Prod is used for 30d log retention, logsearchTestEnv for 2d log retention and 
  prod:
    enabled: false
  windprodlogging:
    enabled: false
  logsearchTestEnv:
    enabled: false
  % if 'containerRegistryBase' in values['global']:
  loggingSetupimage: ${values['global']['containerRegistryBase']}/platform/platform-k8s-tools-minimal:1.3.3_202509080945_master_90384dcc
  % else:
  loggingSetupimage: platform.artifactory.qvantel.net/platform/platform-k8s-tools-minimal:1.3.3_202509080945_master_90384dcc
  % endif
  elasticsearch:
    image:
      % if 'containerRegistryBase' in values['global']:
      registry: ${values['global']['containerRegistryBase']}
      % else:
      registry: docker.io
      % endif
      repository: bitnamilegacy/elasticsearch
      tag: 8.17.1-debian-12-r2
    volumePermissions:
      enabled: true
      image:
        % if 'containerRegistryBase' in values['global']:
        registry: ${values['global']['containerRegistryBase']}
        % else:
        registry: platform.artifactory.qvantel.net
        % endif
        repository: platform/platform-k8s-tools-minimal
        tag: 1.3.3_202509080945_master_90384dcc
    metrics:
      enabled: false
      image:
        % if 'containerRegistryBase' in values['global']:
        registry: ${values['global']['containerRegistryBase']}
        % else:
        registry: docker.io
        % endif
        repository: bitnamilegacy/elasticsearch-exporter
        tag: 1.8.0-debian-12-r9
    sysctlImage:
      enabled: false
      % if 'containerRegistryBase' in values['global']:
      registry: ${values['global']['containerRegistryBase']}
      % else:
      registry: platform.artifactory.qvantel.net
      % endif
      repository: platform/platform-k8s-tools
      tag: 1.3.3_202509080945_master_90384dcc
    global:
      % if 'containerRegistryBase' in values['global']:
      imageRegistry: ${values['global']['containerRegistryBase']}
      % endif
      security:
        allowInsecureImages: true
      elasticsearch:
        service:
          name: logsearch
          ports:
            restAPI: 9200
      kibanaEnabled: false
    fullnameOverride: "${values['global']['helmReleaseNamePrefix']}logsearch-platform"
    security:
    # Enabling this also enables copy-tls-certificates init container which does not get
    # templated correctly - it is hard coded to pull bitnami/os-shell and only respects
    # global.imageRegistry value - if you need this, use a custom registry and ensure
    # it has bitnami/os-shell.
      enabled: false
      existingSecret: "logsearch-elastic"
      tls:
        restEncryption: false
        autoGenerated: true
    master:
      masterOnly: false
      replicaCount: 1
      pdb:
        create: false
      resources:
        requests:
          cpu: 0.1
          memory: 1000Mi
        limits:
          cpu: 2
          memory: 8000Mi
      networkPolicy:
        enabled: false
      persistence:
        size: 50Gi
      persistentVolumeClaimRetentionPolicy:
        enabled: true
        whenScaled: Retain
        whenDeleted: Retain   
      serviceAccount:
        create: false
        name: "platform"
      tolerations:
        - key: "${values['global']['platformMastersKey']}"
          value: "${values['global']['platformMastersValue']}"
          operator: "Equal"
          effect: "NoSchedule"
      % if values['global']['platformMasters']:
      nodeSelector:
        ${values['global']['platformMastersKey']}: ${values['global']['platformMastersValue']}
      % endif
      % if values['global']['multiZone']['enabled']:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: master
              app.kubernetes.io/instance: ${values['global']['helmReleaseNamePrefix']}logsearch-platform
      % endif
    data:
      replicaCount: 0
      pdb:
        create: false
      resources:
        requests:
          cpu: 0.1
          memory: 1000Mi
        limits:
          cpu: 2
          memory: 8000Mi
      networkPolicy:
        enabled: false
      persistence:
        size: 50Gi
      persistentVolumeClaimRetentionPolicy:
        enabled: true
        whenScaled: Retain
        whenDeleted: Retain
      serviceAccount:
        create: false
        name: "platform"
    coordinating:
      replicaCount: 0
      pdb:
        create: false
      resources:
        requests:
          cpu: 0.1
          memory: 1000Mi
        limits:
          cpu: 2
          memory: 8000Mi
      networkPolicy:
        enabled: false
    ingest:
      enabled: false
      replicaCount: 0
      pdb:
        create: false
      resources:
        requests:
          cpu: 0.1
          memory: 1000Mi
        limits:
          cpu: 2
          memory: 8000Mi
      networkPolicy:
        enabled: false
      serviceAccount:
        create: false
        name: "platform"
    copyTlsCerts:
      resourcesPreset: "nano"
    kibana:
      image:
        % if 'containerRegistryBase' in values['global']:
        registry: ${values['global']['containerRegistryBase']}
        % else:
        registry: docker.io
        % endif
        repository: bitnamilegacy/kibana
        tag: 8.17.0-debian-12-r0
      persistence:
        enabled: false
      networkPolicy:
        enabled: false
      resources:
        requests:
          memory: 1000Mi
          cpu: 0.1
        limits:
          cpu: 1
          memory: 1500Mi
      tls:
        enabled: false
        autoGenerated: false
      elasticsearch:
        security:
          auth:
            enabled: true
            existingSecret: "logsearch-kibana-system"
            createSystemUser: true
            elasticsearchPasswordSecret: "logsearch-elastic"
          tls:
            enabled: false
            verificationMode: "full"
            existingSecret: logsearch-platform-master-crt
            usePemCerts: true
        hosts:
        - '{{ include "elasticsearch.service.name" . }}'
        port: '{{ include "elasticsearch.service.ports.restAPI" . }}'