logsearchPlatform:
  # Prod is used for 30d log retention, logsearchTestEnv for 2d log retention and 
  prod:
    enabled: false
  windprodlogging:
    enabled: false
  logsearchTestEnv:
    enabled: false
  % if 'containerRegistryBase' in values['global']:
  loggingSetupimage: ${values['global']['containerRegistryBase']}/platform/platform-k8s-tools-minimal:1.2.0_10_5193dbce5
  % else:
  loggingSetupimage: platform.artifactory.qvantel.net/platform/platform-k8s-tools-minimal:1.2.0_10_5193dbce5
  % endif
  elasticsearch:
    global:
      % if 'containerRegistryBase' in values['global']:
      imageRegistry: ${values['global']['containerRegistryBase']}
      % endif
      security:
        allowInsecureImages: true
      elasticsearch:
        service:
          name: logsearch
          ports:
            restAPI: 9200
      kibanaEnabled: false
    fullnameOverride: "${values['global']['helmReleaseNamePrefix']}logsearch-platform"
    security:
      enabled: true
      existingSecret: "logsearch-elastic"
      tls:
        restEncryption: false
        autoGenerated: true
    master:
      masterOnly: false
      replicaCount: 1
      pdb:
        create: false
      resources:
        requests:
          cpu: 0.1
          memory: 1000Mi
        limits:
          cpu: 2
          memory: 8000Mi
      networkPolicy:
        enabled: false
      persistence:
        size: 50Gi
      persistentVolumeClaimRetentionPolicy:
        enabled: true
        whenScaled: Retain
        whenDeleted: Retain   
      serviceAccount:
        create: false
        name: "platform"
      tolerations:
        - key: "${values['global']['platformMastersKey']}"
          value: "${values['global']['platformMastersValue']}"
          operator: "Equal"
          effect: "NoSchedule"
      % if values['global']['platformMasters']:
      nodeSelector:
        ${values['global']['platformMastersKey']}: ${values['global']['platformMastersValue']}
      % endif
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: master
              app.kubernetes.io/instance: ${values['global']['helmReleaseNamePrefix']}logsearch-platform
    data:
      replicaCount: 0
      pdb:
        create: false
      resources:
        requests:
          cpu: 0.1
          memory: 1000Mi
        limits:
          cpu: 2
          memory: 8000Mi
      networkPolicy:
        enabled: false
      persistence:
        size: 50Gi
      persistentVolumeClaimRetentionPolicy:
        enabled: true
        whenScaled: Retain
        whenDeleted: Retain
      serviceAccount:
        create: false
        name: "platform"
    coordinating:
      replicaCount: 0
      pdb:
        create: false
      resources:
        requests:
          cpu: 0.1
          memory: 1000Mi
        limits:
          cpu: 2
          memory: 8000Mi
      networkPolicy:
        enabled: false
    ingest:
      enabled: false
      replicaCount: 0
      pdb:
        create: false
      resources:
        requests:
          cpu: 0.1
          memory: 1000Mi
        limits:
          cpu: 2
          memory: 8000Mi
      networkPolicy:
        enabled: false
      serviceAccount:
        create: false
        name: "platform"
    sysctlImage:
      enabled: false
    copyTlsCerts:
      resourcesPreset: "nano"
    kibana:
      persistence:
        enabled: false
      networkPolicy:
        enabled: false
      resources:
        requests:
          memory: 1000Mi
          cpu: 0.1
        limits:
          cpu: 1
          memory: 1500Mi
      tls:
        enabled: false
        autoGenerated: false
      elasticsearch:
        security:
          auth:
            enabled: true
            existingSecret: "logsearch-kibana-system"
            createSystemUser: true
            elasticsearchPasswordSecret: "logsearch-elastic"
          tls:
            enabled: false
            verificationMode: "full"
            existingSecret: logsearch-platform-master-crt
            usePemCerts: true
        hosts:
        - '{{ include "elasticsearch.service.name" . }}'
        port: '{{ include "elasticsearch.service.ports.restAPI" . }}'