{{- if .Values.postgresPlatform.clusters }}
{{- range keys .Values.postgresPlatform.clusters  }}
{{- $current := get $.Values.postgresPlatform.clusters . }}
{{- if $current.enabled }}
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ . }}
spec:
  {{- toYaml $current.spec | nindent 2 }}
{{- end }}
{{- end }}
