apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sftp.fullname" . }}
spec:
  {{- if not .Values.sftp.autoscaling.enabled }}
  replicas: {{ .Values.sftp.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sftp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.sftp.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sftp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.sftp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sftp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.sftp.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.sftp.securityContext | nindent 12 }}
          image: "{{ .Values.sftp.image.repository }}:{{ .Values.sftp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.sftp.image.pullPolicy }}
          args: {{ print "\n" (.Values.sftp.users | toYaml | indent 12) }}  
          volumeMounts:
          - name: data
            mountPath: "/home"
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          resources:
            {{- toYaml .Values.sftp.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-sftp-data
      {{- with .Values.sftp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sftp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sftp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}