kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sftp-data
spec:
  accessModes:
    {{- range .Values.sftp.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.sftp.persistence.size | quote }}
  storageClassName: "efs"