apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftp.fullname" . }}
spec:
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    {{- include "sftp.selectorLabels" . | nindent 4 }}