apiVersion: v2
name: kasopePlatform
version: 0.0.1
dependencies:
 - name: k8ssandra-operator
   version: 1.27.0
   repository: https://helm.k8ssandra.io/stable
   condition: k8ssandra-operator.enabled
