---
{{- $password := (randAlphaNum 32) }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace "platform-minio-readwrite").data }}
{{- if $secretData }}
{{- $password = (index $secretData "readwritePassword" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "platform-minio-readwrite"
type: Opaque
data:
  readwriteUser: {{ "platform-minio-readwrite" | b64enc }}
  readwritePassword: {{ $password | b64enc }}