---
{{- $password := (randAscii 32 | b64enc) }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace "platform-minio-root").data }}
{{- if $secretData }}
{{- $password = (index $secretData "rootPassword" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "platform-minio-root"
type: Opaque
data:
  rootUser: {{ "platform-minio-root" | b64enc }}
  rootPassword: {{ $password | b64enc }}