apiVersion: v2
name: loki-platform
version: 0.0.1
dependencies:
  - name: lokiPlatform
    version: 0.0.1
annotations:
  images: |
    - name: loki
      image: docker.io/grafana/loki:3.2.0
    - name: memcached
      image: docker.io/library/memcached:1.6.23-alpine
