apiVersion: v2
name: loki-platform
version: 0.0.1
dependencies:
  - name: lokiPlatform
    version: 0.0.1
annotations:
  images: |
    - name: loki
      image: artifactory.qvantel.net/platform/grafana/loki:2.9.2
