apiVersion: v2
name: loki-platform
version: 0.0.1
dependencies:
  - name: lokiPlatform
    version: 0.0.1
annotations:
  images: |
    - name: loki
      image: platform.artifactory.qvantel.net/k8s-platform-1-2-0/grafana/loki:3.2.0
