lokiPlatform:
  loki:
    enabled: true
    test:
      enabled: false
    monitoring:
      lokiCanary:
        enabled: false
      selfMonitoring:
        enabled: false
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
  promtail:
    enabled: false
    config:
      lokiAddress: http://loki-platform.platform.svc:3100/loki/api/v1/push