---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.7.6
        args:
        - --log-level={{ .Values.externalDns.logLevel }}
        - --interval={{ .Values.externalDns.pollInterval }}
        - --events
        - --source=service
        - --source=ingress
        - --source=istio-gateway
        - --source=istio-virtualservice
        #- --domain-filter=external-dns-test.my-org.com # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
        - --provider=aws
        - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
        - --registry=txt
        - --txt-prefix=extdns.
        - --txt-owner-id={{ .Values.externalDns.route53ZonId }}
        - --aws-assume-role={{ .Values.externalDns.awsAssumeRole }}
        - --annotation-filter={{ .Values.externalDns.annotationFilter }}
        env:
        - name: EXTERNAL_DNS_DRY_RUN
          value: "{{ .Values.externalDns.dryRun }}"
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes and AWS token files