apiVersion: v2
name: mongodbPlatform
version: 0.0.1
dependencies:
#  - name: mongodb
#    version: 13.1.3
#    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    version: 13.1.3
    repository: https://artifactory.qvantel.net/artifactory/helm-platform/