apiVersion: v2
name: rabbitmq-platform
version: 0.0.1
dependencies:
  - name: rabbitmqPlatform
    version: 0.0.1

## No need for images annotations because dependency chart is from Bitnami and already annotated