rabbitmqPlatform:
  rabbitmq:
    # -- Has to be set because Bitnami considers mirror registries insecure
    global: 
      security:
        allowInsecureImages: true
    image:
      % if 'containerRegistryBase' in values['global']:
      registry: ${values['global']['containerRegistryBase']}
      % endif
    # -- More relaxed readiness probe to prevent a deadlock when restarting after an abrupt stop.
    # This is because rabbitmq tries to sync with its peers before becoming fully functional,
    # while Kubernetes OrderedReady policy only starts the next pod once first one is considered
    # ready.
    #
    # Documentation suggests running the Parallel pod management policy, but it is only feasible
    # for existing clusters - new deployments need to be ran with OrderedReady to add new cluster
    # members one by one. In addition adjusting podManagementPolicy is not allowed on the fly,
    # forcing recreating the sateful set.
    #
    # However, since liveness probe defaults to curling /api/health/checks/virtual-hosts,
    # a relaxed readiness probe shouldn't lead to false positives concerning pod health.
    #
    # [RabbitMQ documentation](https://www.rabbitmq.com/docs/clustering#restarting-readiness-probes)
    # [Chart values documentation](https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/values.yaml#L684-L695)
    # [StackOverflow thread with a comment from RMQ developer](https://stackoverflow.com/questions/60407082/rabbit-mq-error-while-waiting-for-mnesia-tables/78439528#78439528)
    customReadinessProbe:
      exec:
        command:
          - sh
          - -ec
          - rabbitmq-diagnostics -q ping
      timeoutSeconds: 10
    auth:
      username: user
      securePassword: true
      existingPasswordSecret: ""
      existingErlangSecret: "rabbitmq-erlang-secret"
      tls:
        enabled: false
        autoGenerated: false
        failIfNoPeerCert: true
        sslOptionsVerify: verify_peer
        caCertificate: |-
        serverCertificate: |-
        serverKey: |-
        existingSecret: ""
        existingSecretFullChain: false

    # -- Enabled rabbitmq plugins
    plugins: "rabbitmq_management, rabbitmq_peer_discovery_k8s, rabbitmq_auth_backend_ldap, rabbitmq_stomp"

    communityPlugins: ""

    # -- Enabled rabbitmq extra plugins
    extraPlugins: "rabbitmq_auth_backend_ldap rabbitmq_web_stomp"

    extraContainerPorts:
      - name: web-stomp
        containerPort: 15674
      - name: stomp
        containerPort: 61613
    service:
      annotations:
        consul.hashicorp.com/service-port: amqp
        platform.qvantel.com/consul-service-port: "5672"
      extraPorts:
      - name: web-stomp
        port: 15674
        targetPort: 15674
      - name: stomp
        port: 61613
        targetPort: 61613
    extraConfiguration: |-
      #default_vhost = {{ .Release.Namespace }}-vhost
      #disk_free_limit.absolute = 50MB

    # -- Number of replicas - Default is one for development profile, three for anything else.
    % if values['global']['configurationProfile'] in {'dev'}:
    replicaCount: 1
    % else:
    replicaCount: 3
    % endif

    resources:
      limits:
        cpu: 1
        ephemeral-storage: 2Gi
        memory: 3072Mi
      requests:
        cpu: 250m
        ephemeral-storage: 50Mi
        memory: 512Mi

    networkPolicy:
      enabled: false
    
    tolerations:
      - key: "${values['global']['platformMastersKey']}"
        value: "${values['global']['platformMastersValue']}"
        operator: "Equal"
        effect: "NoSchedule"
    % if values['global']['platformMasters']:
    nodeSelector:
      ${values['global']['platformMastersKey']}: ${values['global']['platformMastersValue']}
    % endif
    
    volumePermissions:
      enabled: false
      image:
        % if 'containerRegistryBase' in values['global']:
        registry: ${values['global']['containerRegistryBase']}    
        % endif