rabbitmqPlatform:
# 
  rabbitmq:
    auth:
      username: user
      password: "dXNlcg=="
      existingPasswordSecret: ""
      erlangCookie: "OVRGRG5uM1VsYUU5UHdSSm9YY2JBb20zT3Nid0p3NFY="
      existingErlangSecret: ""
      tls:
        enabled: false
        autoGenerated: false
        failIfNoPeerCert: true
        sslOptionsVerify: verify_peer
        caCertificate: |-
        serverCertificate: |-
        serverKey: |-
        existingSecret: ""
        existingSecretFullChain: false

    plugins: "rabbitmq_management, rabbitmq_peer_discovery_k8s, rabbitmq_auth_backend_ldap, rabbitmq_stomp"

    communityPlugins: ""

    extraPlugins: "rabbitmq_auth_backend_ldap rabbitmq_web_stomp"

    extraContainerPorts:
      - name: web-stomp
        containerPort: 15674
      - name: stomp
        containerPort: 61613
    service:
      annotations:
        consul.hashicorp.com/service-port: amqp
      extraPorts:
      - name: web-stomp
        port: 15674
        targetPort: 15674
      - name: stomp
        port: 61613
        targetPort: 61613
    extraConfiguration: |-
      #default_vhost = {{ .Release.Namespace }}-vhost
      #disk_free_limit.absolute = 50MB

    % if values['global']['configurationProfile'] in {'dev'}:
    replicaCount: 1
    % else:
    replicaCount: 3
    % endif
    
    tolerations:
      - key: "dedicated-nodes"
        value: "platform-masters"
        operator: "Equal"
        effect: "NoSchedule"
    % if values['global']['configurationProfile'] in {'perf', 'prod'}:  ### In PERF, PROD we run on dedicated platform-masters nodes
    nodeSelector:
      dedicated-nodes: platform-masters
    % endif
    
    volumePermissions:
      enabled: false
