rabbitmqPlatform:
  rabbitmq:
    global: 
      security:
        allowInsecureImages: true
    image:
      % if 'containerRegistryBase' in values['global']:
      registry: ${values['global']['containerRegistryBase']}
      % endif
    auth:
      username: user
      securePassword: true
      existingPasswordSecret: ""
      existingErlangSecret: "rabbitmq-erlang-secret"
      tls:
        enabled: false
        autoGenerated: false
        failIfNoPeerCert: true
        sslOptionsVerify: verify_peer
        caCertificate: |-
        serverCertificate: |-
        serverKey: |-
        existingSecret: ""
        existingSecretFullChain: false

    plugins: "rabbitmq_management, rabbitmq_peer_discovery_k8s, rabbitmq_auth_backend_ldap, rabbitmq_stomp"

    communityPlugins: ""

    extraPlugins: "rabbitmq_auth_backend_ldap rabbitmq_web_stomp"

    extraContainerPorts:
      - name: web-stomp
        containerPort: 15674
      - name: stomp
        containerPort: 61613
    service:
      annotations:
        consul.hashicorp.com/service-port: amqp
        platform.qvantel.com/consul-service-port: "5672"
      extraPorts:
      - name: web-stomp
        port: 15674
        targetPort: 15674
      - name: stomp
        port: 61613
        targetPort: 61613
    extraConfiguration: |-
      #default_vhost = {{ .Release.Namespace }}-vhost
      #disk_free_limit.absolute = 50MB

    % if values['global']['configurationProfile'] in {'dev'}:
    replicaCount: 1
    % else:
    replicaCount: 3
    % endif

    resources:
      limits:
        cpu: 1
        ephemeral-storage: 2Gi
        memory: 3072Mi
      requests:
        cpu: 250m
        ephemeral-storage: 50Mi
        memory: 512Mi
    
    tolerations:
      - key: "${values['global']['platformMastersKey']}"
        value: "${values['global']['platformMastersValue']}"
        operator: "Equal"
        effect: "NoSchedule"
    % if values['global']['platformMasters']:
    nodeSelector:
      ${values['global']['platformMastersKey']}: ${values['global']['platformMastersValue']}
    % endif
    
    volumePermissions:
      enabled: false
      image:
        % if 'containerRegistryBase' in values['global']:
        registry: ${values['global']['containerRegistryBase']}    
        % endif