{
 "title": "Flex BPMN Process",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "processDefinition",
    "query": "label_values(flex_bpmn_process_started_total,definition)"
   }
  ]
 },
 "panels": [
  {
   "title": "Started",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(flex_bpmn_process_started_total{app!=\"\",definition=\"$processDefinition\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(flex_bpmn_process_completed_total{app!=\"\",definition=\"$processDefinition\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Terminated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(flex_bpmn_process_completed_with_terminate_end_event_total{app!=\"\",definition=\"$processDefinition\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Error",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(flex_bpmn_process_completed_with_error_end_event_total{app!=\"\",definition=\"$processDefinition\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Escalation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(flex_bpmn_process_completed_with_escalation_end_event_total{app!=\"\",definition=\"$processDefinition\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Cancelled",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(flex_bpmn_process_cancelled_total{app!=\"\",definition=\"$processDefinition\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Entered Triggerable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(flex_bpmn_process_in_triggerable_service_task_entered_total{app!=\"\",definition=\"$processDefinition\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Exited Triggerable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(flex_bpmn_process_in_triggerable_service_task_exited_total{definition=\"$processDefinition\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$processDefinition",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 3 },
   "repeat": "processDefinition",
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flex_bpmn_process_started_total{definition=\"$processDefinition\"}[5m]))",
     "legendFormat": "Started"
    },
    {
     "expr": "sum(rate(flex_bpmn_process_completed_total{definition=\"$processDefinition\"}[5m]))",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(rate(flex_bpmn_process_completed_with_error_end_event_total{definition=\"$processDefinition\"}[5m]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(rate(flex_bpmn_process_completed_with_terminate_end_event_total{definition=\"$processDefinition\"}[5m]))",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(rate(flex_bpmn_process_cancelled_total{definition=\"$processDefinition\"}[5m]))",
     "legendFormat": "Cancelled"
    },
    {
     "expr": "sum(rate(flex_bpmn_process_in_triggerable_service_task_entered_total{definition=\"$processDefinition\"}[5m])) - sum(rate(flex_bpmn_process_in_triggerable_service_task_exited_total{definition=\"$processDefinition\"}[5m]))",
     "legendFormat": "Waiting"
    }
   ]
  }
 ]
}