apiVersion: v2
name: istio-platform
version: 0.0.1
dependencies:
  - name: istioPlatform
    version: 0.0.1
annotations:
  images: |
    - name: pilot
      image: docker.io/istio/pilot:1.17.6
    - name: proxyv2
      image: docker.io/istio/proxyv2:1.17.6