apiVersion: v2
name: mariadbOperatorPlatform
version: 0.0.1
dependencies:
#  - name: mariadb-operator
#    version: 0.27.0
#    repository: https://mariadb-operator.github.io/mariadb-operator
  - name: mariadb-operator
    version: 0.27.0
    repository: https://mariadb-operator.github.io/mariadb-operator


