apiVersion: v2
name: istioPlatform
version: 0.0.1
dependencies:
  - name: base
    version: "*"
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: "*"
    repository: https://istio-release.storage.googleapis.com/charts