
{{- if .Values.istioIngress.privateIngressBufferHttpRequestSize  }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: private-ingress-http-req-buffering-filter
  namespace: {{ .Release.Namespace }}
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: with-matcher
          typed_config:
            '@type':  type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher
            extension_config:
              name: envoy.filters.http.buffer
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
                max_request_bytes: {{ .Values.istioIngress.privateIngressBufferHttpRequestSize }}
            xds_matcher:
              matcher_tree:
                input:
                  name: request-headers
                  typed_config:
                    '@type': type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                    header_name: Upgrade
                exact_match_map:
                  map:
                    websocket:
                      action:
                        name: skip
                        typed_config:
                          '@type':  type.googleapis.com/envoy.extensions.filters.common.matcher.action.v3.SkipFilter
  workloadSelector:
    labels:
      istio: {{ .Values.globalConfig.helmReleaseNamePrefix }}private-ingress
{{- end }}

{{- if .Values.istioIngress.publicIngressBufferHttpRequestSize  }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: public-ingress-http-req-buffering-filter
  namespace: {{ .Release.Namespace }}
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: with-matcher
          typed_config:
            '@type':  type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher
            extension_config:
              name: envoy.filters.http.buffer
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
                max_request_bytes: {{ .Values.istioIngress.publicIngressBufferHttpRequestSize }}
            xds_matcher:
              matcher_tree:
                input:
                  name: request-headers
                  typed_config:
                    '@type': type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                    header_name: Upgrade
                exact_match_map:
                  map:
                    websocket:
                      action:
                        name: skip
                        typed_config:
                          '@type':  type.googleapis.com/envoy.extensions.filters.common.matcher.action.v3.SkipFilter
  workloadSelector:
    labels:
      istio: {{ .Values.globalConfig.helmReleaseNamePrefix }}public-ingress
{{- end }}


{{- if .Values.istioIngress.integrationsHttpIngressBufferHttpRequestSize  }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: integrations-http-ingress-http-req-buffering-filter
  namespace: {{ .Release.Namespace }}
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: with-matcher
          typed_config:
            '@type':  type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher
            extension_config:
              name: envoy.filters.http.buffer
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
                max_request_bytes: {{ .Values.istioIngress.integrationsHttpIngressBufferHttpRequestSize }}
            xds_matcher:
              matcher_tree:
                input:
                  name: request-headers
                  typed_config:
                    '@type': type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                    header_name: Upgrade
                exact_match_map:
                  map:
                    websocket:
                      action:
                        name: skip
                        typed_config:
                          '@type':  type.googleapis.com/envoy.extensions.filters.common.matcher.action.v3.SkipFilter
  workloadSelector:
    labels:
      istio: {{ .Values.globalConfig.helmReleaseNamePrefix }}integrations-http-ingress
{{- end }}


{{- if .Values.istioIngress.integrationsNonHttpIngressBufferHttpRequestSize  }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: integrations-non-http-ingress-http-req-buffering-filter
  namespace: {{ .Release.Namespace }}
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: with-matcher
          typed_config:
            '@type':  type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher
            extension_config:
              name: envoy.filters.http.buffer
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
                max_request_bytes: {{ .Values.istioIngress.integrationsNonHttpIngressBufferHttpRequestSize }}
            xds_matcher:
              matcher_tree:
                input:
                  name: request-headers
                  typed_config:
                    '@type': type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                    header_name: Upgrade
                exact_match_map:
                  map:
                    websocket:
                      action:
                        name: skip
                        typed_config:
                          '@type':  type.googleapis.com/envoy.extensions.filters.common.matcher.action.v3.SkipFilter
  workloadSelector:
    labels:
      istio: {{ .Values.globalConfig.helmReleaseNamePrefix }}integrations-non-http-ingress
{{- end }}
