apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:  
  name: istio-public-ingress-telemetry
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      istio: {{ .Values.globalConfig.helmReleaseNamePrefix }}public-ingress
  accessLogging:
  - providers:
    - name: ingress-access-log

---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:  
  name: istio-private-ingress-telemetry
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      istio: {{ .Values.globalConfig.helmReleaseNamePrefix }}private-ingress
  accessLogging:
  - providers:
    - name: ingress-access-log

---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:  
  name: istio-integrations-http-ingress-telemetry
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      istio: {{ .Values.globalConfig.helmReleaseNamePrefix }}integrations-http-ingress
  accessLogging:
  - providers:
    - name: ingress-access-log