{{- if .Values.istioIngress }}
{{- if .Values.istioIngress.virtualServices }}
{{- if .Values.istioIngress.virtualServices.instances }}
{{- $root := . }}
{{- range keys .Values.istioIngress.virtualServices.instances  }}
{{- $current := get $.Values.istioIngress.virtualServices.instances . }}
{{- if $current.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  {{- $empty := dict}}
  {{- $commonAnnotations := (default $empty $.Values.istioIngress.virtualServices.annotations | deepCopy)}}
  {{- $serviceAnnotations := (default $empty $current.annotations | deepCopy)}}
  {{- $joinedAnnotations := merge $serviceAnnotations $commonAnnotations }}
  {{- if $joinedAnnotations }}
  annotations:
    {{- toYaml $joinedAnnotations | nindent 4 }}
  {{- end }}
  name: {{ . }}
spec:
  gateways: {{ print "\n" ($current.gateways | toYaml | indent 2) }} 
  {{- if $current.hosts }}
  {{- with $current.hosts }}
  hosts: 
    {{- tpl (toYaml .) $root | nindent 2 }}
  {{- end }}
  {{- else }}
  hosts: 
  - {{ . }}-{{ $.Values.istioIngress.virtualServices.dnsBase }}
  {{- end }}
  {{- with $current.http }}
  http:
    {{- if and $root.Values.istioIngress.pomeriumEnabled $current.pomeriumProtected }}
    - route:
      - destination:
          host: pomerium-platform-proxy.platform.svc.cluster.local
          port:
            number: 80
    {{- else }}
    {{- tpl (toYaml .) $root | nindent 2 }}
    {{ end }}
    
  {{- end }}
  {{- with $current.tcp }}
  tcp: 
    {{- tpl (toYaml .) $root | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}