opensearchPlatform:
  opensearchEnabled: true
  # -- Enables OpenSearch Dashboards, which is their Kibana equivalent
  opensearchDashboardsEnabled: false
  dataPrepperEnabled: false
  loggingSetup:
    enabled: "true"
    # -- Index configuration - Indices are split in two
    # to long and short term with respective retentions
    shorttermIndices:
      - application
      - audit
    shorttermRetentionPeriod: "2d"
    longtermIndices:
      - ingress
    longtermRetentionPeriod: "45d"

  opensearch:
    clusterName: "${values['global']['helmReleaseNamePrefix']}opensearch-cluster"
    nodeGroup: "master"
    % if values['global']['configurationProfile'] == 'dev':
    singleNode: true
    % endif
    masterService: "${values['global']['helmReleaseNamePrefix']}opensearch-cluster-master"
    roles:
      - master
      - ingest
      - data
      - remote_cluster_client
    replicas: 3

    % if 'containerRegistryBase' in values['global']:
    global:
      dockerRegistry: ${values['global']['containerRegistryBase']}
    % endif

    # -- Secret is generated by [secrets.yaml](./templates/secrets.yaml) - it is used by the admin user.
    envFrom:
    - secretRef:
        name: opensearch-initial-password

    resources:
      requests:
        cpu: "1000m"
        memory: "100Mi"
      limits:
        cpu: "2"
        memory: "8000Mi"

    rbac:
      serviceAccountName: "platform"

    persistence:
      enabled: true
      enableInitChown: true
      % if 'containerRegistryBase' in values['global']:
      image: platform/platform-k8s-tools-minimal
      % else:
      image: platform.artifactory.qvantel.net/platform/platform-k8s-tools-minimal
      % endif
      imageTag: 1.3.3_202509080945_master_90384dcc
      accessModes:
        - ReadWriteOnce
      size: 8Gi

    antiAffinityTopologyKey: "kubernetes.io/hostname"
    antiAffinity: "soft"
    % if values['global']['multiZone']['enabled']:
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: opensearch
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
    % endif

    enableServiceLinks: false
    maxUnavailable: 1

    tolerations:
      - key: "${values['global']['platformMastersKey']}"
        value: "${values['global']['platformMastersValue']}"
        operator: "Equal"
        effect: "NoSchedule"
    % if values['global']['platformMasters']:
    nodeSelector:
      ${values['global']['platformMastersKey']}: ${values['global']['platformMastersValue']}
    % endif

    sysctlInit:
      enabled: false
      # -- Needs to use full tools image, as needs to run 'sysctl'
      % if 'containerRegistryBase' in values['global']:
      image: platform/platform-k8s-tools
      % else:
      image: platform.artifactory.qvantel.net/platform/platform-k8s-tools
      % endif
      imageTag: 1.3.3_202509080945_master_90384dcc

  opensearchDashboards:
    opensearchHosts: "https://${values['global']['helmReleaseNamePrefix']}opensearch-cluster-master.${values['global']['platformNamespace']}.svc:9200"
    replicaCount: 1
    % if 'containerRegistryBase' in values['global']:
    image:
      repository: ${values['global']['containerRegistryBase']}/opensearchproject/opensearch-dashboards:3.3.0
    % endif

    serviceAccount:
      create: false
      name: "platform"

    rbac:
      create: true

    resources:
      requests:
        cpu: "100m"
        memory: "512M"
      limits:
        cpu: "500m"
        memory: "1024M"

    tolerations:
      - key: "${values['global']['platformMastersKey']}"
        value: "${values['global']['platformMastersValue']}"
        operator: "Equal"
        effect: "NoSchedule"
    % if values['global']['platformMasters']:
    nodeSelector:
      ${values['global']['platformMastersKey']}: ${values['global']['platformMastersValue']}
    % endif

  dataPrepper:
    % if 'containerRegistryBase' in values['global']:
    global:
      dockerRegistry: ${values['global']['containerRegistryBase']}
    % endif

    serviceAccount:
      create: false
      name: "platform"

    tolerations:
      - key: "${values['global']['platformMastersKey']}"
        value: "${values['global']['platformMastersValue']}"
        operator: "Equal"
        effect: "NoSchedule"
    % if values['global']['platformMasters']:
    nodeSelector:
      ${values['global']['platformMastersKey']}: ${values['global']['platformMastersValue']}
    % endif