---
## OpenSearch admin password, username is "admin"
{{- $password := (randAscii 32 | b64enc) }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace "opensearch-initial-password").data }}
{{- if $secretData }}
{{- $password = (index $secretData "OPENSEARCH_INITIAL_ADMIN_PASSWORD" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: "opensearch-initial-password"
type: Opaque
data:
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: {{ $password | b64enc }}
---
## OpenSearch readwrite crendentials, used by Vector
{{- $osdbsecret := (randAscii 32 | b64enc) }}
{{- $osdbsecretData := (lookup "v1" "Secret" .Release.Namespace "opensearch-dashboards-readwrite").data }}
{{- if $osdbsecretData }}
{{- $osdbsecret = (index $osdbsecretData "password" | b64dec) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-dashboards-readwrite
type: Opaque
data:
  username: {{ "readwrite" | b64enc }}
  password: {{ $osdbsecret | b64enc }}