apiVersion: v2
name: artifactory-platform
version: 0.0.1
dependencies:
  - name: artifactoryPlatform
    version: 0.0.1
annotations:
  images: |
    - name: artifactory-oss
      image: platform.artifactory.qvantel.net/k8s-platform-1-2-0/jfrog/artifactory-oss:7.90.5
    - name: artifactory-jcr
      image: platform.artifactory.qvantel.net/k8s-platform-1-2-0/jfrog/artifactory-jcr:7.90.5
    - name: router
      image: platform.artifactory.qvantel.net/k8s-platform-1-2-0/jfrog/router:7.118.0
    - name: init-container
      image: platform.artifactory.qvantel.net/k8s-platform-1-2-0/ubi9/ubi-minimal:9.4-1194
