apiVersion: v2
name: artifactory-platform
version: 0.0.1
dependencies:
  - name: artifactoryPlatform
    version: 0.0.1
annotations:
  images: |
    - name: artifactory-oss
      image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.117.17
    - name: artifactory-jcr
      image: releases-docker.jfrog.io/jfrog/artifactory-jcr:7.117.17
    - name: router
      image: releases-docker.jfrog.io/jfrog/router:7.177.6
    - name: init-container
      image: platform.artifactory.qvantel.net/platform/platform-k8s-tools-minimal:1.3.3_202509080945_master_90384dcc