monitoringPlatform:
  grafana:
    enabled: true
    adminPassword: Q4nt3l321
    plugins:
      - grafana-piechart-panel
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Viewer
    sidecar:
      datasources:
        enabled: true
        maxLines: 1000
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
         - name: 'cluster'
           orgId: 1
           folder: ''
           type: file
           disableDeletion: false
           editable: true
           options:
             path: /var/lib/grafana/dashboards/cluster
         - name: 'bssapi'
           orgId: 1
           folder: ''
           type: file
           disableDeletion: false
           editable: true
           options:
             path: /var/lib/grafana/dashboards/bssapi
         - name: 'summary'
           orgId: 1
           folder: ''
           type: file
           disableDeletion: false
           editable: true
           options:
             path: /var/lib/grafana/dashboards/summary
         - name: 'capacity'
           orgId: 1
           folder: ''
           type: file
           disableDeletion: false
           editable: true
           options:
             path: /var/lib/grafana/dashboards/capacity
         - name: 'flex-bpmn-processes'
           orgId: 1
           folder: ''
           type: file
           disableDeletion: false
           editable: true
           options:
             path: /var/lib/grafana/dashboards/flex-bpmn-processes
         - name: 'flex-bpmn-processes-overview'
           orgId: 1
           folder: ''
           type: file
           disableDeletion: false
           editable: true
           options:
             path: /var/lib/grafana/dashboards/flex-bpmn-processes-overview
         - name: 'jvm-monitoring'
           orgId: 1
           folder: ''
           type: file
           disableDeletion: false
           editable: true
           options:
             path: /var/lib/grafana/dashboards/jvm-monitoring
         - name: 'persistent-volumes'
           orgId: 1
           folder: ''
           type: file
           disableDeletion: false
           editable: true
           options:
             path: /var/lib/grafana/dashboards/persistent-volumes
         - name: 'orders-overview'
           orgId: 1
           folder: ''
           type: file
           disableDeletion: false
           editable: true
           options:
             path: /var/lib/grafana/dashboards/orders-overview
         - name: 'rid'
           orgId: 1
           folder: ''
           type: file
           disableDeletion: false
           editable: true
           options:
             path: /var/lib/grafana/dashboards/rid
    dashboardsConfigMaps:
      cluster: "grafana-dashboards-cluster"
      bssapi: "grafana-dashboards-bssapi"
      summary: "grafana-dashboards-summary"
      capacity: "grafana-dashboards-capacity"
      flex-bpmn-processes: "grafana-dashboards-flex-bpmn-processes"
      flex-bpmn-processes-overview: "grafana-dashboards-flex-bpmn-processes-overview"
      jvm-monitoring: "grafana-dashboards-jvm-monitoring"
      persistent-volumes: "grafana-dashboards-persistent-volumes"
      orders-overview: "grafana-dashboards-orders-overview"
      rid: "grafana-dashboards-rid"
  loki:
    enabled: true
  promtail:
    enabled: true
    config:
      lokiAddress: http://monitoring-platform-loki.platform.svc:3100/loki/api/v1/push
  prometheus:
    enabled: true
    server:
# mount alerts at `/etc/config/alerts`
      extraConfigmapMounts:
        - name: prometheus-alerts
          mountPath: /etc/config/alerts
          configMap: prometheus-alerts
          readOnly: true
    serverFiles:
# configure Prometheus-server to look at `/etc/config/alerts` for alert files
      prometheus.yml:
        rule_files:
          - /etc/config/rules/*.yaml
          - /etc/config/alerts/*.yml
# configmap-reload container to mount the prometheus-alerts configmap also and to trigger hot reload of alerts
    configmapReload:
      prometheus:
        enabled: true
        name: configmap-reload
        extraConfigmapMounts:
            - name: prometheus-alerts
              mountPath: /etc/alerts.d
              subPath: ""
              configMap: prometheus-alerts
              readOnly: true
        extraVolumeDirs:
          - /etc/alerts.d