apiVersion: v2
name: istioIngress
version: 0.0.1
dependencies:
  - name: gateway
    alias: privateIngress
    condition: privateIngress.enabled
    version: "1.13.2"
    repository: https://istio-release.storage.googleapis.com/charts
  - name: gateway
    alias: publicIngress
    condition: publicIngress.enabled
    version: "1.13.2"
    repository: https://istio-release.storage.googleapis.com/charts
  - name: gateway
    alias: integrationsIngress
    condition: integrationsIngress.enabled
    version: "1.13.2"
    repository: https://istio-release.storage.googleapis.com/charts