awsPlatform:
  aws-load-balancer-controller-enabled: true
  aws-load-balancer-controller:
    clusterName: cluster-name
    serviceAccount:
      name: platform
      create: false
  aws-efs-csi-driver-enabled: false
  aws-efs-csi-driver:
    controller:
      serviceAccount:
        create: false
        name: platform
    node:
      serviceAccount:
        create: false
        name: platform
    storageClasses:
      # Add StorageClass resources like:
      - name: efs-sc
        #   annotations:
        #     # Use that annotation if you want this to your default storageclass
        #     storageclass.kubernetes.io/is-default-class: "true"
        mountOptions:
          - tls
        parameters:
          provisioningMode: efs-ap
          fileSystemId: SYSTEM_EFS_VALUE_HERE
          directoryPerms: "700"
          # gidRangeStart: "1000"
          # gidRangeEnd: "2000"
          uid: "0"
          gid: "0"
          basePath: "/dynamic_provisioning"
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
  aws-ebs-csi-driver-enabled: false
  aws-ebs-csi-driver:
    controller:
      serviceAccount:
        create: false
        name: platform
    node:
      serviceAccount:
        create: false
        name: platform
    storageClasses:
      - name: gp3
        # annotation metadata
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
        # defaults to WaitForFirstConsumer
        volumeBindingMode: WaitForFirstConsumer
        # defaults to Delete
        reclaimPolicy: Delete
        parameters:
          type: gp3
