redisPlatform:
  redis:    
    architecture: replication
    auth:
      enabled: true
      sentinel: true
    master:
      resources:
        limits: {}
        requests: {}      
      persistence:
        enabled: true
        storageClass: ""
        size: 8Gi
    replica:
      replicaCount: 2      
      resources:
        limits: {}
        requests: {}      
      persistence:
        enabled: true        
        storageClass: ""        
        size: 8Gi      
    sentinel:
      enabled: false
      masterSet: mymaster
      quorum: 2
      getMasterTimeout: 220
      automateClusterRecovery: false
      downAfterMilliseconds: 60000
      failoverTimeout: 18000      
      resources:
        limits: {}
        requests: {}      
    metrics:
      enabled: true