redisPlatform:
  redis:
    architecture: replication
    auth:
      enabled: true
      sentinel: true
    master:
      resources:
        limits: {}
        requests: {}
      persistence:
        enabled: true
        storageClass: ""
        size: 8Gi
    replica:
      replicaCount: 3
      resources:
        limits: {}
        requests: {}
      persistence:
        enabled: true
        storageClass: ""
        size: 8Gi
    sentinel:
      enabled: true
      masterSet: redis
      quorum: 2
      resources:
        limits: {}
        requests: {}
      service:
        annotations:
          consul.hashicorp.com/service-port: tcp-sentinel
    metrics:
      enabled: true
