apiVersion: v2
name: kyverno-platform
version: 0.0.1
dependencies:
  - name: kyvernoPlatform
    version: 0.0.1
annotations:
  images: |
    - name: kyverno-cli
      image: reg.kyverno.io/kyverno/kyverno-cli:v1.15.2
    - name: tools
      image: platform.artifactory.qvantel.net/platform/platform-k8s-tools-minimal:1.3.3_202509080945_master_90384dcc
    - name: kyvernopre
      image: reg.kyverno.io/kyverno/kyvernopre:v1.15.2
    - name: kyverno
      image: reg.kyverno.io/kyverno/kyverno:v1.15.2
    - name: background-controller
      image: reg.kyverno.io/kyverno/background-controller:v1.15.2
    - name: cleanup-controller
      image: reg.kyverno.io/kyverno/cleanup-controller:v1.15.2
    - name: reports-controller
      image: reg.kyverno.io/kyverno/reports-controller:v1.15.2