apiVersion: v2
name: elasticsearchPlatform
version: 0.0.1
dependencies:
  - name: eck-operator
    version: 3.1.0
    repository: https://helm.elastic.co
    condition: eck-operator.enabled
  - name: logstash
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: logstashEnabled
  - name: eck-beats
    version: 0.16.0
    repository: https://helm.elastic.co
    condition: filebeatEnabled