from os import environ
ADDON_OPERATOR_CONFIG_MAP = environ.get('ADDON_OPERATOR_CONFIG_MAP', 'addon-operator')
ADDON_OPERATOR_DEPLOY_RESOURCES = environ.get('ADDON_OPERATOR_DEPLOY_RESOURCES', 'true')
ADDON_OPERATOR_NAMESPACE = environ.get('ADDON_OPERATOR_NAMESPACE', 'platform')
SHUTDOWN_OPERATOR_NAMESPACE = environ.get('SHUTDOWN_OPERATOR_NAMESPACE', 'platform-shutdown')
ADDON_OPERATOR_OUTPUT_HELM_RESOURCES = environ.get('ADDON_OPERATOR_OUTPUT_HELM_RESOURCES', 'false')

HELM_RELEASE_NAME_PREFIX= environ.get('HELM_RELEASE_NAME_PREFIX', '')

VAULT_RELEASE_NAME = environ.get('VAULT_RELEASE_NAME', HELM_RELEASE_NAME_PREFIX+'vault-platform')
VAULT_ADDR = environ.get('VAULT_ADDR', 'http://' + VAULT_RELEASE_NAME + '.' + ADDON_OPERATOR_NAMESPACE + '.svc.cluster.local:8200')
VAULT_SECRET_NAME = environ.get('VAULT_SECRET_NAME', 'vault-keys')
VAULT_SECRET_NAMESPACE = environ.get('VAULT_SECRET_NAMESPACE', ADDON_OPERATOR_NAMESPACE)
VAULT_SECRET_ROOT_TOKEN = environ.get('VAULT_SECRET_ROOT_TOKEN', 'root_token')

CONSUL_HOST = environ.get('CONSUL_HOST', HELM_RELEASE_NAME_PREFIX + 'consul-platform-consul-server.' + ADDON_OPERATOR_NAMESPACE + '.svc')
CONSUL_PORT = environ.get('CONSUL_PORT', 8500)
CONSUL_SCHEME = environ.get('CONSUL_SCHEME', 'http')
