ADDON_OPERATOR_CONFIG_MAP=${ADDON_OPERATOR_CONFIG_MAP:-"addon-operator"}
ADDON_OPERATOR_DEPLOY_RESOURCES=${ADDON_OPERATOR_DEPLOY_RESOURCES:-"true"}
ADDON_OPERATOR_NAMESPACE=${ADDON_OPERATOR_NAMESPACE:-"platform"}
ADDON_OPERATOR_OUTPUT_HELM_RESOURCES=${ADDON_OPERATOR_OUTPUT_HELM_RESOURCES:-"false"}

HELM_RELEASE_NAME_PREFIX=${HELM_RELEASE_NAME_PREFIX:-""}

ISTIO_RELEASE_NAME="${HELM_RELEASE_NAME_PREFIX}istio-platform"
ISTIO_RELEASE_NAMESPACE=${ISTIO_RELEASE_NAMESPACE:-"$ADDON_OPERATOR_NAMESPACE"}

VAULT_RELEASE_NAME="${HELM_RELEASE_NAME_PREFIX}vault-platform"
VAULT_ADDR=${VAULT_ADDR:-"http://$VAULT_RELEASE_NAME.$ADDON_OPERATOR_NAMESPACE.svc.cluster.local:8200"}
VAULT_SECRET_NAME=${VAULT_SECRET_NAME:-"vault-keys"}
VAULT_SECRET_NAMESPACE=${VAULT_SECRET_NAMESPACE:-"$ADDON_OPERATOR_NAMESPACE"}
VAULT_SECRET_ROOT_TOKEN=${VAULT_SECRET_ROOT_TOKEN:-"root_token"}

CONSUL_HOST=${CONSUL_HOST:-"consul-platform-consul-server.$ADDON_OPERATOR_NAMESPACE.svc"}
CONSUL_PORT=${CONSUL_PORT:-"8500"}
CONSUL_SCHEME=${CONSUL_SCHEME:-"http"}
