ADDON_OPERATOR_DEPLOY_RESOURCES=${ADDON_OPERATOR_DEPLOY_RESOURCES:-"true"}
ADDON_OPERATOR_NAMESPACE=${ADDON_OPERATOR_NAMESPACE:-"platform"}
HELM_RELEASE_NAME_PREFIX=${HELM_RELEASE_NAME_PREFIX:-""}
VAULT_RELEASE_NAME="${HELM_RELEASE_NAME_PREFIX}vault-platform"
VAULT_ADDR=${VAULT_ADDR:-"http://$VAULT_RELEASE_NAME.$ADDON_OPERATOR_NAMESPACE.svc.cluster.local:8200"}
VAULT_SECRET_NAME=${VAULT_SECRET_NAME:-"vault-keys"}
VAULT_SECRET_NAMESPACE=${VAULT_SECRET_NAMESPACE:-"$ADDON_OPERATOR_NAMESPACE"}
VAULT_SECRET_ROOT_TOKEN=${VAULT_SECRET_ROOT_TOKEN:-"root_token"}