VAULT_ADDR=${VAULT_ADDR:-"http://vault-platform.platform.svc.cluster.local:8200"}
VAULT_SECRET_NAME=${VAULT_SECRET_NAME:-"vault-keys"}
VAULT_SECRET_NAMESPACE=${VAULT_SECRET_NAMESPACE:-"platform"}
VAULT_SECRET_ROOT_TOKEN=${VAULT_SECRET_ROOT_TOKEN:-"root_token"}