istioIngress:
  publicIngressEnabled: true
  publicIngress:
    name: public-ingress
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "external"
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
        service.beta.kubernetes.io/aws-load-balancer-internal: "false"
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  privateIngressEnabled: true
  privateIngress:
    name: private-ingress
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "external"
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  integrationsIngressEnabled: true
  integrationsIngress:
    name: integrations-ingress
  virtualServices:
    public:
      annotations:
        # external-dns.alpha.kubernetes.io/target: my-global-load-balancer.cloud.com
      dnsBase: pbl-qvantel-finland.qvantel.systems
      instances:        
    private:
      dnsBase: prv-qvantel-finland.qvantel.systems
      instances: 
        vault-ui:
          gateway:
          http:
            - route:
                - destination:
                    host: vault-platform-ui.platform.svc.cluster.local
                    port:
                      number: 8200
        consul-ui:
          disabled:
          http:
            - route:
                - destination:
                    host: consul-platform-consul-ui.platform.svc.cluster.local
                    port:
                      number: 80
        kafka-ui:
          disabled:
          http:
            - route:
                - destination:
                    host: kafka-ui.platform.svc.cluster.local
                    port:
                      number: 8080
    integrations:
      dnsBase: int-qvantel-finland.qvantel.systems
      instances: 