# istioIngressNamespace: istio-ingress
istioIngress:
  gateway:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "false"
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        proxy.istio.io/config: '{"gatewayTopology" : { "numTrustedProxies": 2 } }'


