apiVersion: v2
name: kafka-platform
version: 0.0.1
dependencies:
  - name: kafkaPlatform
    version: 0.0.1
annotations:
  images: |
    - name: operator-043
      image: quay.io/strimzi/operator:0.43.0
    - name: operator-0451
      image: quay.io/strimzi/operator:0.45.1
    - name: kafka-043-380
      image: quay.io/strimzi/kafka:0.43.0-kafka-3.8.0
    - name: kafka-0451-391
      image: quay.io/strimzi/kafka:0.45.1-kafka-3.9.1
    - name: kafka-bridge-030
      image: quay.io/strimzi/kafka-bridge:0.30.0
    - name: kafka-bridge-0311
      image: quay.io/strimzi/kafka-bridge:0.31.1
    - name: kaniko-executor-043
      image: quay.io/strimzi/kaniko-executor:0.43.0
    - name: kaniko-executor-0451
      image: quay.io/strimzi/kaniko-executor:0.45.1
    - name: maven-builder-043
      image: quay.io/strimzi/maven-builder:0.43.0
    - name: maven-builder-0451
      image: quay.io/strimzi/maven-builder:0.45.1
    - name: kafka-ui
      image: ghcr.io/kafbat/kafka-ui:v1.3.0
