kafkaPlatform:
  kafka:
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      partitions: 3
      autoCreateTopics: "true"
    storage:
      size: 100Gi
  zookeeper:
    storage:
      size: 100Gi
