apiVersion: v2
name: keycloak-platform
version: 0.0.1
annotations:
  images: |
    - name: keycloak
      image: artifactory.qvantel.net/qvaa-keycloak-qrp-postgres-quarkus:26.1.2.1.20250211132528_master_f8fcbe3c
    - name: keycloak-configurator
      image: artifactory.qvantel.net/keycloak-configurator-standalone:1.18.1.20250115062040_develop_c85e3e6d
