# keycloakPlatformNamespace: keycloak
keycloakPlatform:
  adminUsername: "admin"
  adminPassword: "" # set keycloak admin password or leave empty to be autogenerated
  pomeriumSecretName: pomerium-platform-shared # must match pomeriumPlatform.pomerium.config.existingSharedSecret
  database:
    name: qvt-postgredb
  configurator:
    image: "artifactory.qvantel.net/qinstaller-keycloak-configurator:1.13.1.20231201141851_develop_32d2199d"
    spec: |
      backoffLimit: 5
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: keycloak-configurator
            image: {{ .Values.keycloakPlatform.configurator.image }}
            command:
            - /opt/docker/configurator.py
            volumeMounts:
              - name: config-volume
                mountPath: "/config"
                readOnly: true
            env:
              # this must match keycloak kubernetes "service"
              - name: KEYCLOAK_BASE
                value: "http://qvaa-proxy-80.platform.svc/auth"
              # this must match the mount and the configmap file in the mount
              - name: CONFIGURATOR_CONFIG
                value: /config/configurator.yml
              % if addon_operator['pomeriumPlatformEnabled'] == 'true':
              - name: POMERIUM_CLIENT_SECRET
                # https://stash.qvantel.net/projects/CP/repos/k8s-platform-addon-operator/browse/modules/315-pomerium-platform/templates/shared-secret.yaml
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.keycloakPlatform.pomeriumSecretName }}
                    key: IDP_CLIENT_SECRET
              % endif
              % if addon_operator['monitoringPlatformEnabled'] == 'true':
              - name: GRAFANA_CLIENT_SECRET
                # https://stash.qvantel.net/projects/CP/repos/k8s-platform-addon-operator/browse/modules/110-monitoring-platform/templates/secrets/grafana_keycloak_client_secret.yaml
                valueFrom:
                  secretKeyRef:
                    name: grafana-keycloak-client-secret
                    key: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              % endif
            envFrom:
              - secretRef:
                  name: keycloak-admin-secret
          volumes:
            - name: config-volume
              projected:
                sources:
                  - configMap:
                      name: configurator-configmap
                      items:
                        - key: configurator.yml
                          path: configurator.yml
    configmap: |
      configurator.yml: |
        ---
        realms:
          qvantel:
            clients:
              # note: all clients will be created, regardless if they are used.
              # if the module is not defined and the secret does not exist,
              # there will a random secret generated.
              pomerium:
                % if addon_operator['pomeriumPlatformEnabled'] == 'true':
                secret: $POMERIUM_CLIENT_SECRET
                % endif
                redirect_uris:
                  # pomerium shares domain name with keycloak
                  - https://auth-${values['global']['ingressBaseUrl']}/*
              grafana:
                % if addon_operator['pomeriumPlatformEnabled'] == 'true':
                secret: $GRAFANA_CLIENT_SECRET
                % endif
                roles_claim: realm_access.roles
                pkce: S256
                redirect_uris:
                  - https://grafana-${values['global']['ingressBaseUrl']}/*
  deployment:
    additionalLabels: null
    replicaCount: 1
    image: "artifactory.qvantel.net/qvaa-keycloak-qrp-postgres-quarkus:23.0.4.2.20240116085404_master_9cdb6973"
    # command: [ "some-command" ]
    # args: [ "--some-option" ]
    % if values['global']['configurationProfile'] in {'perf', 'prod'}:
    # depending on keycloak use, even more could be needed, but this is a good starting point.
    metaspace: 512m
    maxMetaspace: 512m
    xms: 1024m
    xmx: 1024m
    memory: 2G
    cpu: 200m
    % else:
    metaspace: 256m
    maxMetaspace: 256m
    xms: 512m
    xmx: 512m
    memory: 1G
    cpu: 100m
    % endif
    spec: |
      progressDeadlineSeconds: 600
      replicas: {{ .Values.keycloakPlatform.deployment.replicaCount }}
      % if values['global']['configurationProfile'] == 'dev':
      # in single host environments pod affinity prevents rolling update because second pod can't run on same host
      strategy:
        type: Recreate
      % endif
      selector:
        matchLabels:
          app: qvaa-keycloak
      template:
        metadata:
          annotations:
            app.kubernetes.io/name: keycloak
            vault.security.banzaicloud.io/enable-json-log: "true"
            vault.security.banzaicloud.io/log-level: warn
            vault.security.banzaicloud.io/vault-addr: http://vault.platform.svc:8200
            vault.security.banzaicloud.io/vault-env-daemon: "true"
            vault.security.banzaicloud.io/vault-ignore-missing-secrets: "false"
            vault.security.banzaicloud.io/vault-role: platform-qvaa-keycloak
          labels:
            app: qvaa-keycloak
        spec:
          serviceAccountName: keycloak
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - qvaa-keycloak
                topologyKey: kubernetes.io/hostname
          containers:
          - env:
            - name: APP_DOCKER_IMAGE
              value: {{ .Values.keycloakPlatform.deployment.image }}
            - name: METASPACE_SIZE
              value: {{ .Values.keycloakPlatform.deployment.metaspace }}
            - name: KC_LOG_LEVEL
              value: info,org.keycloak.events:debug
            - name: SERVICE_NAME
              value: qvaa-keycloak
            - name: MAX_METASPACE_SIZE
              value: {{ .Values.keycloakPlatform.deployment.maxMetaspace }}
            - name: XMX
              value: {{ .Values.keycloakPlatform.deployment.xmx }}
            - name: XMS
              value: {{ .Values.keycloakPlatform.deployment.xms }}
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://qvt-postgredb.platform.svc/keycloak
            - name: KC_DB_USERNAME
              value: vault:database/creds/postgresql_qvaa-keycloak#username
            - name: KC_DB_PASSWORD
              value: vault:database/creds/postgresql_qvaa-keycloak#password
            - name: INSTANA_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            envFrom:
              - secretRef:
                  name: keycloak-admin-secret
            image: {{ .Values.keycloakPlatform.deployment.image }}
            {{- if .Values.keycloakPlatform.deployment.command }}
            command: {{ .Values.keycloakPlatform.deployment.command }}
            {{- end }}
            {{- if .Values.keycloakPlatform.deployment.args }}
            args: {{ .Values.keycloakPlatform.deployment.args }}
            {{- end }}
            imagePullPolicy: IfNotPresent
            livenessProbe:
              failureThreshold: 3
              httpGet:
                httpHeaders:
                - name: CheckType
                  value: liveness
                path: /auth/health
                port: 80
                scheme: HTTP
              initialDelaySeconds: 300
              periodSeconds: 60
              successThreshold: 1
              timeoutSeconds: 20
            name: qvaa-keycloak
            ports:
            - containerPort: 80
              protocol: TCP
            readinessProbe:
              failureThreshold: 3
              httpGet:
                httpHeaders:
                - name: CheckType
                  value: readiness
                path: /auth/health
                port: 80
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 9
            resources:
              limits:
                memory: {{ .Values.keycloakPlatform.deployment.memory }}
              requests:
                cpu: {{ .Values.keycloakPlatform.deployment.cpu }}
