# keycloakPlatformNamespace: keycloak
keycloakPlatform:
  adminUsername: "admin"
  adminPassword: "" # set keycloak admin password or leave empty to be autogenerated
  vaultIntegration:
    enabled: false
    # https://developer.hashicorp.com/vault/docs/auth/jwt
    # an issue with vault keycloak integration is, vault needs to contact to the "external" url of
    # keycloak, https://auth-... because it expects to "issuer" to match the url.
    # because of this, keycloak integration is not enabled by default.
    discovery_url: https://auth${values['global']['ingressBaseUrlSeparator']}${values['global']['ingressBaseUrl']}/auth/realms/qvantel
    vault_url: https://vault-ui${values['global']['ingressBaseUrlSeparator']}${values['global']['ingressBaseUrl']}/ui/vault/auth/oidc/oidc/callback
    oidc_discovery_ca_pem: false
    policies:
      policyreadonly: |
        path "secret/*" {
          capabilities = ["list"]
        }

        path "secret/data/platform/readonly/*" {
          capabilities = ["read"]
        }
      policysecretappsadmin: |
        path "secret/*" {
          capabilities = ["read", "list", "create", "update", "patch", "delete"]
        }

        path "secret/data/installer/qvaa/*" {
          capabilities = ["deny"]
        }
      policydbro: |
        path "database/*" {
          capabilities = ["list"]
        }

        path "database/creds/readonly-role*" {
          capabilities = ["read"]
        }
      policydbrw: |
        path "database/*" {
          capabilities = ["list"]
        }

        path "database/creds/readwrite-role*" {
          capabilities = ["read"]
        }
      policyadmin: |
        path "*" {
          capabilities = ["read", "list", "create", "update", "delete", "sudo"]
        }

    groups:
      groupreadonly:
        policies:
          - policyreadonly
        value: vault-readonly
      groupdbro:
        policies:
          - policydbro
        value: vault-dbro
      groupdbrw:
        policies:
          - policydbrw
        value: vault-dbrw
      groupappsadmin:
        policies:
          - policysecretappsadmin
        value: vault-appsadmin
        # this value needs to match keycloak role
      groupadmin:
        policies:
          - policyadmin
        value: vault-admins
  pomeriumSecretName: pomerium-platform-shared # must match pomeriumPlatform.pomerium.config.existingSharedSecret
  sftpgoSecretName: sftpgo-shared-secrets # must match sftpgoPlatform.secrets.existingSecretName
  database:
    name: qvt-postgredb
  configurator:
    image: ${values['global']['containerRegistryBase']}/keycloak-configurator-standalone:1.18.1.20250115062040_develop_c85e3e6d
    spec: |
      backoffLimit: 5
      template:
        spec:
          restartPolicy: Never
          tolerations:
            - key: "${values['global']['platformMastersKey']}"
              value: "${values['global']['platformMastersValue']}"
              operator: "Equal"
              effect: "NoSchedule"
          containers:
          - name: keycloak-configurator
            image: {{ .Values.keycloakPlatform.configurator.image }}
            command:
            - /opt/docker/configurator.py
            volumeMounts:
              - name: config-volume
                mountPath: "/config"
                readOnly: true
            env:
              # this must match keycloak kubernetes "service"
              - name: KEYCLOAK_BASE
                value: "http://qvaa-proxy-80.${values['global']['platformNamespace']}.svc/auth"
              # this must match the mount and the configmap file in the mount
              - name: CONFIGURATOR_CONFIG
                value: /config/configurator.yml
              % if addon_operator['pomeriumPlatformEnabled'] == 'true':
              - name: POMERIUM_CLIENT_SECRET
                # https://stash.qvantel.net/projects/CP/repos/k8s-platform-addon-operator/browse/modules/315-pomerium-platform/templates/shared-secret.yaml
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.keycloakPlatform.pomeriumSecretName }}
                    key: IDP_CLIENT_SECRET
              % endif
              % if addon_operator['kafkaPlatformEnabled'] == 'true':
              - name: KAFKA_UI_CLIENT_SECRET
                # https://stash.qvantel.net/projects/CP/repos/k8s-platform-addon-operator/browse/modules/220-kafka-platform/templates/kafka-ui-client-secret.yaml?at=b6ec5cfebbcc33b11b0c9e75a8a15bfabf303bfa
                valueFrom:
                  secretKeyRef:
                    name: kafka-ui-client-secret
                    key: KAFKA_UI_CLIENT_SECRET
              % endif
              % if addon_operator['monitoringPlatformEnabled'] == 'true':
              - name: GRAFANA_CLIENT_SECRET
                # https://stash.qvantel.net/projects/CP/repos/k8s-platform-addon-operator/browse/modules/110-monitoring-platform/templates/secrets/grafana_keycloak_client_secret.yaml
                valueFrom:
                  secretKeyRef:
                    name: grafana-keycloak-client-secret
                    key: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              % endif
              % if addon_operator['sftpgoPlatformEnabled'] == 'true':
              - name: SFTPGO_CLIENT_SECRET
                # https://stash.qvantel.net/projects/CP/repos/k8s-platform-addon-operator/browse/modules/411-sftpgo-platform/templates/secrets.yaml
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.keycloakPlatform.sftpgoSecretName }}
                    key: SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET
              % endif
              - name: VAULT_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: vault-client-secret
                    key: VAULT_CLIENT_SECRET
            envFrom:
              - secretRef:
                  name: keycloak-admin-secret
          volumes:
            - name: config-volume
              projected:
                sources:
                  - configMap:
                      name: configurator-configmap
                      items:
                        - key: configurator.yml
                          path: configurator.yml
    configmap: |
      configurator.yml: |
        ---
        realms:
          qvantel:
            clients:
              # note: all clients will be created, regardless if they are used.
              # if the module is not defined and the secret does not exist,
              # there will a random secret generated.
              pomerium:
                % if addon_operator['pomeriumPlatformEnabled'] == 'true':
                secret: $POMERIUM_CLIENT_SECRET
                % endif
                redirect_uris:
                  # pomerium shares domain name with keycloak
                  - https://auth${values['global']['ingressBaseUrlSeparator']}${values['global']['ingressBaseUrl']}/*
                roles_claim: realm_access.roles
              grafana:
                % if addon_operator['pomeriumPlatformEnabled'] == 'true':
                secret: $GRAFANA_CLIENT_SECRET
                % endif
                roles_claim: realm_access.roles
                pkce: S256
                redirect_uris:
                  - https://grafana${values['global']['ingressBaseUrlSeparator']}${values['global']['ingressBaseUrl']}/*
              kafbat:
                % if addon_operator['kafkaPlatformEnabled'] == 'true':
                secret: $KAFKA_UI_CLIENT_SECRET
                % endif
                roles_claim: roles
                redirect_uris:
                  - https://kafka-ui${values['global']['ingressBaseUrlSeparator']}${values['global']['ingressBaseUrl']}/*
              sftpgo:
                % if addon_operator['sftpgoPlatformEnabled'] == 'true':
                secret: $SFTPGO_CLIENT_SECRET
                % endif
                mappers:
                  - type: sftpgo
                    name: sftpgomapper
                redirect_uris:
                  # this is a guess, no sftpgo in https://stash.qvantel.net/projects/CP/repos/k8s-platform-addon-operator/browse/modules/151-istio-ingress/values.yaml.mako
                  - https://sftpgo${values['global']['ingressBaseUrlSeparator']}${values['global']['ingressBaseUrl']}/*
              vault:
                secret: $VAULT_CLIENT_SECRET
                roles_claim: realm_access.roles
                redirect_uris:
                  - http://localhost:8250/oidc/callback
                  - https://vault-ui${values['global']['ingressBaseUrlSeparator']}${values['global']['ingressBaseUrl']}/*
            roles:
              kafka-admins: {}
              kafka-readonly: {}
              consul-admins: {}
              consul-readonly: {}
              prometheus-admins: {}
              prometheus-readonly: {}
              sftpgo-admins: {}
              vault-admins: {}
              vault-appsadmin: {}
              vault-dbro: {}
              vault-dbrw: {}
              vault-readonly: {}
              grafana_server_admin:
                description: "Grafana server administrator permissions: Manage Grafana server-wide settings and resources"
              grafana_admin:
                description: "Organization administrator: Has access to all organization resources, including dashboards, users, and teams."
              grafana_editor:
                description: "Editor: Can view and edit dashboards, folders, and playlists."
              grafana_viewer:
                description: "Viewer: Can view dashboards and playlists."
  deployment:
    additionalLabels: null
    replicaCount: 1
    image: ${values['global']['containerRegistryBase']}/qvaa-keycloak-qrp-postgres-quarkus:24.0.5.4.20240819100502_hotfix-24_d5c69cea
    # keycloak 25 moved health to a separate port 9000 https://www.keycloak.org/docs/latest/release_notes/index.html#management-port-for-metrics-and-health-endpoints
    healthPort: 8080
    # command: [ "some-command" ]
    # args: [ "--some-option" ]
    extraEnv: []
    % if values['global']['configurationProfile'] in {'perf', 'prod'}:
    # depending on keycloak use, even more could be needed, but this is a good starting point.
    metaspace: 512m
    maxMetaspace: 512m
    xms: 1024m
    xmx: 1024m
    memory: 2G
    cpu: 200m
    % else:
    metaspace: 256m
    maxMetaspace: 256m
    xms: 512m
    xmx: 512m
    memory: 1G
    cpu: 100m
    % endif
    spec: |
      progressDeadlineSeconds: 600
      replicas: {{ .Values.keycloakPlatform.deployment.replicaCount }}
      % if values['global']['configurationProfile'] == 'dev':
      # in single host environments pod affinity prevents rolling update because second pod can't run on same host
      strategy:
        type: Recreate
      % endif
      selector:
        matchLabels:
          app: qvaa-keycloak
      template:
        metadata:
          annotations:
            app.kubernetes.io/name: keycloak
            vault.security.banzaicloud.io/enable-json-log: "true"
            vault.security.banzaicloud.io/log-level: warn
            vault.security.banzaicloud.io/vault-addr: http://vault.${values['global']['platformNamespace']}.svc:8200
            vault.security.banzaicloud.io/vault-env-daemon: "true"
            vault.security.banzaicloud.io/vault-ignore-missing-secrets: "false"
            vault.security.banzaicloud.io/vault-role: platform-qvaa-keycloak
          labels:
            app: qvaa-keycloak
            security.banzaicloud.io/mutate: apply
        spec:
          serviceAccountName: keycloak
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - qvaa-keycloak
                topologyKey: kubernetes.io/hostname
          containers:
          - env:
            - name: APP_DOCKER_IMAGE
              value: {{ .Values.keycloakPlatform.deployment.image }}
            - name: METASPACE_SIZE
              value: {{ .Values.keycloakPlatform.deployment.metaspace }}
            - name: KC_LOG_LEVEL
              value: info,org.keycloak.events:debug
            - name: SERVICE_NAME
              value: qvaa-keycloak
            - name: MAX_METASPACE_SIZE
              value: {{ .Values.keycloakPlatform.deployment.maxMetaspace }}
            - name: XMX
              value: {{ .Values.keycloakPlatform.deployment.xmx }}
            - name: XMS
              value: {{ .Values.keycloakPlatform.deployment.xms }}
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://qvt-postgredb.${values['global']['platformNamespace']}.svc/keycloak
            - name: KC_DB_USERNAME
              value: vault:database/creds/postgresql_qvaa-keycloak#username
            - name: KC_DB_PASSWORD
              value: vault:database/creds/postgresql_qvaa-keycloak#password
            - name: KC_HTTP_PORT
              value: "8080"
            - name: INSTANA_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            {{- range .Values.keycloakPlatform.deployment.extraEnv }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
            envFrom:
              - secretRef:
                  name: keycloak-admin-secret
            image: {{ .Values.keycloakPlatform.deployment.image }}
            {{- if .Values.keycloakPlatform.deployment.command }}
            command: {{ .Values.keycloakPlatform.deployment.command }}
            {{- end }}
            {{- if .Values.keycloakPlatform.deployment.args }}
            args: {{ .Values.keycloakPlatform.deployment.args }}
            {{- end }}
            imagePullPolicy: IfNotPresent
            livenessProbe:
              failureThreshold: 3
              httpGet:
                httpHeaders:
                - name: CheckType
                  value: liveness
                path: /auth/health
                port: {{ .Values.keycloakPlatform.deployment.healthPort }}
                scheme: HTTP
              initialDelaySeconds: 300
              periodSeconds: 60
              successThreshold: 1
              timeoutSeconds: 20
            name: qvaa-keycloak
            ports:
            - containerPort: 8080
              protocol: TCP
            readinessProbe:
              failureThreshold: 3
              httpGet:
                httpHeaders:
                - name: CheckType
                  value: readiness
                path: /auth/health
                port: {{ .Values.keycloakPlatform.deployment.healthPort }}
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 9
            resources:
              limits:
                memory: {{ .Values.keycloakPlatform.deployment.memory }}
              requests:
                cpu: {{ .Values.keycloakPlatform.deployment.cpu }}
