apiVersion: v2
name: awsPlatform
version: 0.0.1
dependencies:
  - name: aws-load-balancer-controller
    version: "1.4.1"
    repository: https://aws.github.io/eks-charts
  - name: aws-efs-csi-driver
    version: 2.2.6
    repository: https://kubernetes-sigs.github.io/aws-efs-csi-driver/
