---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-pcd-leader
    redis_setup_type: cluster
    role: leader
  name: redis-cluster-redis-pcd
spec:
  ports:
  - name: redis-client
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-pcd-leader
    redis_setup_type: cluster
    role: leader
# type: LoadBalancer
  type: ClusterIP